// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Provenance of a build. Contains all information needed to verify the full
/// details about the build from source to completion.
public struct BuildProvenance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Unique identifier of the build.
  public var id: Swift.String = Swift.String()

  /// ID of the project.
  public var projectId: Swift.String = Swift.String()

  /// Commands requested by the build.
  public var commands: [Command] = []

  /// Output of the build.
  public var builtArtifacts: [Artifact] = []

  /// Time at which the build was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Time at which execution of the build was started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Time at which execution of the build was finished.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// E-mail address of the user who initiated this build. Note that this was the
  /// user's e-mail address at the time the build was initiated; this address may
  /// not represent the same end-user for all time.
  public var creator: Swift.String = Swift.String()

  /// URI where any logs for this provenance were written.
  public var logsUri: Swift.String = Swift.String()

  /// Details of the Source input to the build.
  public var sourceProvenance: Source? = nil

  /// Trigger identifier if the build was triggered automatically; empty if not.
  public var triggerId: Swift.String = Swift.String()

  /// Special options applied to this build. This is a catch-all field where
  /// build providers can enter any desired additional details.
  public var buildOptions: [Swift.String: Swift.String] = [:]

  /// Version string of the builder at the time this build was executed.
  public var builderVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BuildProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildProvenance().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let id = CodingKeys(stringValue: "id")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let commands = CodingKeys(stringValue: "commands")
    static let builtArtifacts = CodingKeys(stringValue: "builtArtifacts")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let logsUri = CodingKeys(stringValue: "logsUri")
    static let sourceProvenance = CodingKeys(stringValue: "sourceProvenance")
    static let triggerId = CodingKeys(stringValue: "triggerId")
    static let buildOptions = CodingKeys(stringValue: "buildOptions")
    static let builderVersion = CodingKeys(stringValue: "builderVersion")

    static let _knownKeys: Set<Swift.String> = [
      "id",
      "projectId",
      "commands",
      "builtArtifacts",
      "createTime",
      "startTime",
      "endTime",
      "creator",
      "logsUri",
      "sourceProvenance",
      "triggerId",
      "buildOptions",
      "builderVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent([Command].self, forKey: .commands) {
      self.commands = value
    }
    if let value = try container.decodeIfPresent([Artifact].self, forKey: .builtArtifacts) {
      self.builtArtifacts = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .creator) {
      self.creator = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logsUri) {
      self.logsUri = value
    }
    self.sourceProvenance = try container.decodeIfPresent(Source.self, forKey: .sourceProvenance)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .triggerId) {
      self.triggerId = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .buildOptions)
    {
      self.buildOptions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .builderVersion) {
      self.builderVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.commands, forKey: .commands)
    try container.encode(self.builtArtifacts, forKey: .builtArtifacts)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.creator, forKey: .creator)
    try container.encode(self.logsUri, forKey: .logsUri)
    try container.encodeIfPresent(self.sourceProvenance, forKey: .sourceProvenance)
    try container.encode(self.triggerId, forKey: .triggerId)
    try container.encode(self.buildOptions, forKey: .buildOptions)
    try container.encode(self.builderVersion, forKey: .builderVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.BuildProvenance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
