// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details of a build occurrence.
public struct BuildOccurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The actual provenance for the build.
  public var provenance: BuildProvenance? = nil

  /// Serialized JSON representation of the provenance, used in generating the
  /// build signature in the corresponding build note. After verifying the
  /// signature, `provenance_bytes` can be unmarshalled and compared to the
  /// provenance to confirm that it is unchanged. A base64-encoded string
  /// representation of the provenance bytes is used for the signature in order
  /// to interoperate with openssl which expects this format for signature
  /// verification.
  ///
  /// The serialized form is captured both to avoid ambiguity in how the
  /// provenance is marshalled to json as well to prevent incompatibilities with
  /// future changes.
  public var provenanceBytes: Swift.String = Swift.String()

  /// Deprecated. See InTotoStatement for the replacement.
  /// In-toto Provenance representation as defined in spec.
  public var intotoProvenance: InTotoProvenance? = nil

  /// In-toto Statement representation as defined in spec.
  /// The intoto_statement can contain any type of provenance. The serialized
  /// payload of the statement can be stored and signed in the Occurrence's
  /// envelope.
  public var intotoStatement: InTotoStatement? = nil

  /// In-Toto Slsa Provenance V1 represents a slsa provenance meeting the slsa
  /// spec, wrapped in an in-toto statement. This allows for direct
  /// jsonification of a to-spec in-toto slsa statement with a to-spec
  /// slsa provenance.
  public var inTotoSlsaProvenanceV1: InTotoSlsaProvenanceV1? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BuildOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildOccurrence().with { $0.provenance = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let provenance = CodingKeys(stringValue: "provenance")
    static let provenanceBytes = CodingKeys(stringValue: "provenanceBytes")
    static let intotoProvenance = CodingKeys(stringValue: "intotoProvenance")
    static let intotoStatement = CodingKeys(stringValue: "intotoStatement")
    static let inTotoSlsaProvenanceV1 = CodingKeys(stringValue: "inTotoSlsaProvenanceV1")

    static let _knownKeys: Set<Swift.String> = [
      "provenance",
      "provenanceBytes",
      "intotoProvenance",
      "intotoStatement",
      "inTotoSlsaProvenanceV1",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.provenance = try container.decodeIfPresent(BuildProvenance.self, forKey: .provenance)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .provenanceBytes) {
      self.provenanceBytes = value
    }
    self.intotoProvenance = try container.decodeIfPresent(
      InTotoProvenance.self, forKey: .intotoProvenance)
    self.intotoStatement = try container.decodeIfPresent(
      InTotoStatement.self, forKey: .intotoStatement)
    self.inTotoSlsaProvenanceV1 = try container.decodeIfPresent(
      InTotoSlsaProvenanceV1.self, forKey: .inTotoSlsaProvenanceV1)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.provenance, forKey: .provenance)
    try container.encode(self.provenanceBytes, forKey: .provenanceBytes)
    try container.encodeIfPresent(self.intotoProvenance, forKey: .intotoProvenance)
    try container.encodeIfPresent(self.intotoStatement, forKey: .intotoStatement)
    try container.encodeIfPresent(self.inTotoSlsaProvenanceV1, forKey: .inTotoSlsaProvenanceV1)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.BuildOccurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
