// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct ComplianceNote: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The title that identifies this compliance check.
  public var title: Swift.String = Swift.String()

  /// A description about this compliance check.
  public var description: Swift.String = Swift.String()

  /// The OS and config versions the benchmark applies to.
  public var version: [ComplianceVersion] = []

  /// A rationale for the existence of this compliance check.
  public var rationale: Swift.String = Swift.String()

  /// A description of remediation steps if the compliance check fails.
  public var remediation: Swift.String = Swift.String()

  /// Serialized scan instructions with a predefined format.
  public var scanInstructions: Foundation.Data = Foundation.Data()

  public var complianceType: OneOf_ComplianceType? = nil

  /// Potential impact of the suggested remediation
  public var potentialImpact: OneOf_PotentialImpact? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComplianceNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComplianceNote().with { $0.title = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let title = CodingKeys(stringValue: "title")
    static let description = CodingKeys(stringValue: "description")
    static let version = CodingKeys(stringValue: "version")
    static let rationale = CodingKeys(stringValue: "rationale")
    static let remediation = CodingKeys(stringValue: "remediation")
    static let cisBenchmark = CodingKeys(stringValue: "cisBenchmark")
    static let scanInstructions = CodingKeys(stringValue: "scanInstructions")
    static let impact = CodingKeys(stringValue: "impact")

    static let _knownKeys: Set<Swift.String> = [
      "title",
      "description",
      "version",
      "rationale",
      "remediation",
      "cisBenchmark",
      "scanInstructions",
      "impact",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([ComplianceVersion].self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rationale) {
      self.rationale = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remediation) {
      self.remediation = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .scanInstructions) {
      self.scanInstructions = value
    }

    var complianceType: OneOf_ComplianceType? = nil
    let complianceTypeCheckAndSet = {
      if complianceType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'complianceType'"))
      }
      complianceType = $0
    }
    if let cisBenchmark = try container.decodeIfPresent(
      ComplianceNote.CisBenchmark?.self, forKey: .cisBenchmark)
    {
      try complianceTypeCheckAndSet(.cisBenchmark(cisBenchmark))
    }
    self.complianceType = complianceType

    var potentialImpact: OneOf_PotentialImpact? = nil
    let potentialImpactCheckAndSet = {
      if potentialImpact != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'potentialImpact'"))
      }
      potentialImpact = $0
    }
    if let impact = try container.decodeIfPresent(Swift.String.self, forKey: .impact) {
      try potentialImpactCheckAndSet(.impact(impact))
    }
    self.potentialImpact = potentialImpact
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.rationale, forKey: .rationale)
    try container.encode(self.remediation, forKey: .remediation)
    try container.encode(self.scanInstructions, forKey: .scanInstructions)

    if let choice = self.complianceType {
      switch choice {
      case .cisBenchmark(let value):
        try container.encode(value, forKey: .cisBenchmark)
      }
    }

    if let choice = self.potentialImpact {
      switch choice {
      case .impact(let value):
        try container.encode(value, forKey: .impact)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A compliance check that is a CIS benchmark.
  public struct CisBenchmark: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var profileLevel: Swift.Int32 = Swift.Int32()

    public var severity: Severity = Severity()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CisBenchmark`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CisBenchmark().with { $0.profileLevel = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let profileLevel = CodingKeys(stringValue: "profileLevel")
      static let severity = CodingKeys(stringValue: "severity")

      static let _knownKeys: Set<Swift.String> = [
        "profileLevel",
        "severity",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .profileLevel) {
        self.profileLevel = value
      }
      if let value = try container.decodeIfPresent(Severity.self, forKey: .severity) {
        self.severity = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.profileLevel, forKey: .profileLevel)
      try container.encode(self.severity, forKey: .severity)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.ComplianceNote.CisBenchmark"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_ComplianceType: Codable, Equatable, Sendable {
    indirect case cisBenchmark(ComplianceNote.CisBenchmark?)
  }

  /// Potential impact of the suggested remediation
  public enum OneOf_PotentialImpact: Codable, Equatable, Sendable {
    case impact(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.ComplianceNote"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
