// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Indicates that the builder claims certain fields in this message to be
/// complete.
public struct Completeness: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// If true, the builder claims that recipe.arguments is complete, meaning that
  /// all external inputs are properly captured in the recipe.
  public var arguments: Swift.Bool = Swift.Bool()

  /// If true, the builder claims that recipe.environment is claimed to be
  /// complete.
  public var environment: Swift.Bool = Swift.Bool()

  /// If true, the builder claims that materials are complete, usually through
  /// some controls to prevent network access. Sometimes called "hermetic".
  public var materials: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Completeness`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Completeness().with { $0.arguments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let arguments = CodingKeys(stringValue: "arguments")
    static let environment = CodingKeys(stringValue: "environment")
    static let materials = CodingKeys(stringValue: "materials")

    static let _knownKeys: Set<Swift.String> = [
      "arguments",
      "environment",
      "materials",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .arguments) {
      self.arguments = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .environment) {
      self.environment = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .materials) {
      self.materials = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.arguments, forKey: .arguments)
    try container.encode(self.environment, forKey: .environment)
    try container.encode(self.materials, forKey: .materials)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Completeness"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
