// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An indication that the compliance checks in the associated ComplianceNote
/// were not satisfied for particular resources or a specified reason.
public struct ComplianceOccurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var nonCompliantFiles: [NonCompliantFile] = []

  public var nonComplianceReason: Swift.String = Swift.String()

  /// The OS and config version the benchmark was run on.
  public var version: ComplianceVersion? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComplianceOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComplianceOccurrence().with { $0.nonCompliantFiles = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let nonCompliantFiles = CodingKeys(stringValue: "nonCompliantFiles")
    static let nonComplianceReason = CodingKeys(stringValue: "nonComplianceReason")
    static let version = CodingKeys(stringValue: "version")

    static let _knownKeys: Set<Swift.String> = [
      "nonCompliantFiles",
      "nonComplianceReason",
      "version",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [NonCompliantFile].self, forKey: .nonCompliantFiles)
    {
      self.nonCompliantFiles = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nonComplianceReason) {
      self.nonComplianceReason = value
    }
    self.version = try container.decodeIfPresent(ComplianceVersion.self, forKey: .version)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.nonCompliantFiles, forKey: .nonCompliantFiles)
    try container.encode(self.nonComplianceReason, forKey: .nonComplianceReason)
    try container.encodeIfPresent(self.version, forKey: .version)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.ComplianceOccurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
