// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Common Vulnerability Scoring System.
/// For details, see https://www.first.org/cvss/specification-document
/// This is a message we will try to use for storing various versions of CVSS
/// rather than making a separate proto for storing a specific version.
public struct CVSS: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The base score is a function of the base metric scores.
  public var baseScore: Swift.Float = Swift.Float()

  public var exploitabilityScore: Swift.Float = Swift.Float()

  public var impactScore: Swift.Float = Swift.Float()

  /// Attack Vector (AV). Defined in CVSS v2, v3, v4.
  public var attackVector: CVSS.AttackVector = CVSS.AttackVector()

  /// Attack Complexity (AC). Defined in CVSS v2, v3, v4.
  public var attackComplexity: CVSS.AttackComplexity = CVSS.AttackComplexity()

  /// Authentication (Au). Defined in CVSS v2.
  public var authentication: CVSS.Authentication = CVSS.Authentication()

  /// Privileges Required (PR). Defined in CVSS v3, v4.
  public var privilegesRequired: CVSS.PrivilegesRequired = CVSS.PrivilegesRequired()

  /// User Interaction (UI). Defined in CVSS v3, v4.
  public var userInteraction: CVSS.UserInteraction = CVSS.UserInteraction()

  /// Scope (S). Defined in CVSS v3.
  public var scope: CVSS.Scope = CVSS.Scope()

  /// Confidentiality Impact (C). Defined in CVSS v2, v3.
  public var confidentialityImpact: CVSS.Impact = CVSS.Impact()

  /// Integrity Impact (I). Defined in CVSS v2, v3.
  public var integrityImpact: CVSS.Impact = CVSS.Impact()

  /// Availability Impact (A). Defined in CVSS v2, v3.
  public var availabilityImpact: CVSS.Impact = CVSS.Impact()

  /// Attack Requirements (AT). Defined in CVSS v4.
  public var attackRequirements: CVSS.AttackRequirements = CVSS.AttackRequirements()

  /// Vulnerable System Confidentiality Impact (VC). Defined in CVSS v4.
  public var vulnerableSystemConfidentialityImpact: CVSS.Impact = CVSS.Impact()

  /// Vulnerable System Integrity Impact (VI). Defined in CVSS v4.
  public var vulnerableSystemIntegrityImpact: CVSS.Impact = CVSS.Impact()

  /// Vulnerable System Availability Impact (VA). Defined in CVSS v4.
  public var vulnerableSystemAvailabilityImpact: CVSS.Impact = CVSS.Impact()

  /// Subsequent System Confidentiality Impact (SC). Defined in CVSS v4.
  public var subsequentSystemConfidentialityImpact: CVSS.Impact = CVSS.Impact()

  /// Subsequent System Integrity Impact (SI). Defined in CVSS v4.
  public var subsequentSystemIntegrityImpact: CVSS.Impact = CVSS.Impact()

  /// Subsequent System Availability Impact (SA). Defined in CVSS v4.
  public var subsequentSystemAvailabilityImpact: CVSS.Impact = CVSS.Impact()

  /// Exploit Maturity (E). Defined in CVSS v4.
  public var exploitMaturity: CVSS.ExploitMaturity = CVSS.ExploitMaturity()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CVSS`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CVSS().with { $0.baseScore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let baseScore = CodingKeys(stringValue: "baseScore")
    static let exploitabilityScore = CodingKeys(stringValue: "exploitabilityScore")
    static let impactScore = CodingKeys(stringValue: "impactScore")
    static let attackVector = CodingKeys(stringValue: "attackVector")
    static let attackComplexity = CodingKeys(stringValue: "attackComplexity")
    static let authentication = CodingKeys(stringValue: "authentication")
    static let privilegesRequired = CodingKeys(stringValue: "privilegesRequired")
    static let userInteraction = CodingKeys(stringValue: "userInteraction")
    static let scope = CodingKeys(stringValue: "scope")
    static let confidentialityImpact = CodingKeys(stringValue: "confidentialityImpact")
    static let integrityImpact = CodingKeys(stringValue: "integrityImpact")
    static let availabilityImpact = CodingKeys(stringValue: "availabilityImpact")
    static let attackRequirements = CodingKeys(stringValue: "attackRequirements")
    static let vulnerableSystemConfidentialityImpact = CodingKeys(
      stringValue: "vulnerableSystemConfidentialityImpact")
    static let vulnerableSystemIntegrityImpact = CodingKeys(
      stringValue: "vulnerableSystemIntegrityImpact")
    static let vulnerableSystemAvailabilityImpact = CodingKeys(
      stringValue: "vulnerableSystemAvailabilityImpact")
    static let subsequentSystemConfidentialityImpact = CodingKeys(
      stringValue: "subsequentSystemConfidentialityImpact")
    static let subsequentSystemIntegrityImpact = CodingKeys(
      stringValue: "subsequentSystemIntegrityImpact")
    static let subsequentSystemAvailabilityImpact = CodingKeys(
      stringValue: "subsequentSystemAvailabilityImpact")
    static let exploitMaturity = CodingKeys(stringValue: "exploitMaturity")

    static let _knownKeys: Set<Swift.String> = [
      "baseScore",
      "exploitabilityScore",
      "impactScore",
      "attackVector",
      "attackComplexity",
      "authentication",
      "privilegesRequired",
      "userInteraction",
      "scope",
      "confidentialityImpact",
      "integrityImpact",
      "availabilityImpact",
      "attackRequirements",
      "vulnerableSystemConfidentialityImpact",
      "vulnerableSystemIntegrityImpact",
      "vulnerableSystemAvailabilityImpact",
      "subsequentSystemConfidentialityImpact",
      "subsequentSystemIntegrityImpact",
      "subsequentSystemAvailabilityImpact",
      "exploitMaturity",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .baseScore) {
      self.baseScore = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .exploitabilityScore) {
      self.exploitabilityScore = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .impactScore) {
      self.impactScore = value
    }
    if let value = try container.decodeIfPresent(CVSS.AttackVector.self, forKey: .attackVector) {
      self.attackVector = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.AttackComplexity.self, forKey: .attackComplexity)
    {
      self.attackComplexity = value
    }
    if let value = try container.decodeIfPresent(CVSS.Authentication.self, forKey: .authentication)
    {
      self.authentication = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.PrivilegesRequired.self, forKey: .privilegesRequired)
    {
      self.privilegesRequired = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.UserInteraction.self, forKey: .userInteraction)
    {
      self.userInteraction = value
    }
    if let value = try container.decodeIfPresent(CVSS.Scope.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent(CVSS.Impact.self, forKey: .confidentialityImpact) {
      self.confidentialityImpact = value
    }
    if let value = try container.decodeIfPresent(CVSS.Impact.self, forKey: .integrityImpact) {
      self.integrityImpact = value
    }
    if let value = try container.decodeIfPresent(CVSS.Impact.self, forKey: .availabilityImpact) {
      self.availabilityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.AttackRequirements.self, forKey: .attackRequirements)
    {
      self.attackRequirements = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .vulnerableSystemConfidentialityImpact)
    {
      self.vulnerableSystemConfidentialityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .vulnerableSystemIntegrityImpact)
    {
      self.vulnerableSystemIntegrityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .vulnerableSystemAvailabilityImpact)
    {
      self.vulnerableSystemAvailabilityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .subsequentSystemConfidentialityImpact)
    {
      self.subsequentSystemConfidentialityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .subsequentSystemIntegrityImpact)
    {
      self.subsequentSystemIntegrityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.Impact.self, forKey: .subsequentSystemAvailabilityImpact)
    {
      self.subsequentSystemAvailabilityImpact = value
    }
    if let value = try container.decodeIfPresent(
      CVSS.ExploitMaturity.self, forKey: .exploitMaturity)
    {
      self.exploitMaturity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.baseScore, forKey: .baseScore)
    try container.encode(self.exploitabilityScore, forKey: .exploitabilityScore)
    try container.encode(self.impactScore, forKey: .impactScore)
    try container.encode(self.attackVector, forKey: .attackVector)
    try container.encode(self.attackComplexity, forKey: .attackComplexity)
    try container.encode(self.authentication, forKey: .authentication)
    try container.encode(self.privilegesRequired, forKey: .privilegesRequired)
    try container.encode(self.userInteraction, forKey: .userInteraction)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.confidentialityImpact, forKey: .confidentialityImpact)
    try container.encode(self.integrityImpact, forKey: .integrityImpact)
    try container.encode(self.availabilityImpact, forKey: .availabilityImpact)
    try container.encode(self.attackRequirements, forKey: .attackRequirements)
    try container.encode(
      self.vulnerableSystemConfidentialityImpact, forKey: .vulnerableSystemConfidentialityImpact)
    try container.encode(
      self.vulnerableSystemIntegrityImpact, forKey: .vulnerableSystemIntegrityImpact)
    try container.encode(
      self.vulnerableSystemAvailabilityImpact, forKey: .vulnerableSystemAvailabilityImpact)
    try container.encode(
      self.subsequentSystemConfidentialityImpact, forKey: .subsequentSystemConfidentialityImpact)
    try container.encode(
      self.subsequentSystemIntegrityImpact, forKey: .subsequentSystemIntegrityImpact)
    try container.encode(
      self.subsequentSystemAvailabilityImpact, forKey: .subsequentSystemAvailabilityImpact)
    try container.encode(self.exploitMaturity, forKey: .exploitMaturity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Attack Vector.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AttackVector: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Attack Vector: Network (AV:N). Defined in CVSS v2, v3, v4.
    case network
    /// Attack Vector: Adjacent (AV:A). Defined in CVSS v2, v3, v4.
    case adjacent
    ///  Attack Vector: Local (AV:L). Defined in CVSS v2, v3, v4.
    case local
    /// Attack Vector: Physical (AV:P). Defined in CVSS v3, v4.
    case physical
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .network: return 1
      case .adjacent: return 2
      case .local: return 3
      case .physical: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ATTACK_VECTOR_UNSPECIFIED"
      case .network: return "ATTACK_VECTOR_NETWORK"
      case .adjacent: return "ATTACK_VECTOR_ADJACENT"
      case .local: return "ATTACK_VECTOR_LOCAL"
      case .physical: return "ATTACK_VECTOR_PHYSICAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AttackVector/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ATTACK_VECTOR_UNSPECIFIED": self = .unspecified
      case "ATTACK_VECTOR_NETWORK": self = .network
      case "ATTACK_VECTOR_ADJACENT": self = .adjacent
      case "ATTACK_VECTOR_LOCAL": self = .local
      case "ATTACK_VECTOR_PHYSICAL": self = .physical
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AttackVector/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .network
      case 2: self = .adjacent
      case 3: self = .local
      case 4: self = .physical
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ATTACK_VECTOR_UNSPECIFIED")
      case .network: return try container.encode("ATTACK_VECTOR_NETWORK")
      case .adjacent: return try container.encode("ATTACK_VECTOR_ADJACENT")
      case .local: return try container.encode("ATTACK_VECTOR_LOCAL")
      case .physical: return try container.encode("ATTACK_VECTOR_PHYSICAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Attack Complexity.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AttackComplexity: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Low attack complexity (AC:L). Defined in CVSS v2, v3, v4.
    case low
    /// High attack complexity (AC:H). Defined in CVSS v2, v3, v4.
    case high
    /// Medium attack complexity (AC:M). Defined in CVSS v2.
    case medium
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .high: return 2
      case .medium: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ATTACK_COMPLEXITY_UNSPECIFIED"
      case .low: return "ATTACK_COMPLEXITY_LOW"
      case .high: return "ATTACK_COMPLEXITY_HIGH"
      case .medium: return "ATTACK_COMPLEXITY_MEDIUM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AttackComplexity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ATTACK_COMPLEXITY_UNSPECIFIED": self = .unspecified
      case "ATTACK_COMPLEXITY_LOW": self = .low
      case "ATTACK_COMPLEXITY_HIGH": self = .high
      case "ATTACK_COMPLEXITY_MEDIUM": self = .medium
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AttackComplexity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .high
      case 3: self = .medium
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ATTACK_COMPLEXITY_UNSPECIFIED")
      case .low: return try container.encode("ATTACK_COMPLEXITY_LOW")
      case .high: return try container.encode("ATTACK_COMPLEXITY_HIGH")
      case .medium: return try container.encode("ATTACK_COMPLEXITY_MEDIUM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Authentication.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Authentication: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Multiple authentication required (Au:M). Defined in CVSS v2.
    case multiple
    /// Single authentication required (Au:S). Defined in CVSS v2.
    case single
    /// No authentication required (Au:N). Defined in CVSS v2.
    case `none`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .multiple: return 1
      case .single: return 2
      case .`none`: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTHENTICATION_UNSPECIFIED"
      case .multiple: return "AUTHENTICATION_MULTIPLE"
      case .single: return "AUTHENTICATION_SINGLE"
      case .`none`: return "AUTHENTICATION_NONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Authentication/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTHENTICATION_UNSPECIFIED": self = .unspecified
      case "AUTHENTICATION_MULTIPLE": self = .multiple
      case "AUTHENTICATION_SINGLE": self = .single
      case "AUTHENTICATION_NONE": self = .`none`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Authentication/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .multiple
      case 2: self = .single
      case 3: self = .`none`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AUTHENTICATION_UNSPECIFIED")
      case .multiple: return try container.encode("AUTHENTICATION_MULTIPLE")
      case .single: return try container.encode("AUTHENTICATION_SINGLE")
      case .`none`: return try container.encode("AUTHENTICATION_NONE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Privileges Required.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PrivilegesRequired: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// No privileges required (PR:N). Defined in CVSS v3, v4.
    case `none`
    /// Low privileges required (PR:L). Defined in CVSS v3, v4.
    case low
    /// High privileges required (PR:H). Defined in CVSS v3, v4.
    case high
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .low: return 2
      case .high: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PRIVILEGES_REQUIRED_UNSPECIFIED"
      case .`none`: return "PRIVILEGES_REQUIRED_NONE"
      case .low: return "PRIVILEGES_REQUIRED_LOW"
      case .high: return "PRIVILEGES_REQUIRED_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PrivilegesRequired/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PRIVILEGES_REQUIRED_UNSPECIFIED": self = .unspecified
      case "PRIVILEGES_REQUIRED_NONE": self = .`none`
      case "PRIVILEGES_REQUIRED_LOW": self = .low
      case "PRIVILEGES_REQUIRED_HIGH": self = .high
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PrivilegesRequired/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .low
      case 3: self = .high
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PRIVILEGES_REQUIRED_UNSPECIFIED")
      case .`none`: return try container.encode("PRIVILEGES_REQUIRED_NONE")
      case .low: return try container.encode("PRIVILEGES_REQUIRED_LOW")
      case .high: return try container.encode("PRIVILEGES_REQUIRED_HIGH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// User Interaction.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum UserInteraction: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// No user interaction required (UI:N). Defined in CVSS v3, v4.
    case `none`
    /// User interaction required (UI:R). Defined in CVSS v3.
    case `required`
    /// Passive user interaction required (UI:P). Defined in CVSS v4.
    case passive
    /// Active user interaction required (UI:A). Defined in CVSS v4.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .`required`: return 2
      case .passive: return 3
      case .active: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "USER_INTERACTION_UNSPECIFIED"
      case .`none`: return "USER_INTERACTION_NONE"
      case .`required`: return "USER_INTERACTION_REQUIRED"
      case .passive: return "USER_INTERACTION_PASSIVE"
      case .active: return "USER_INTERACTION_ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UserInteraction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "USER_INTERACTION_UNSPECIFIED": self = .unspecified
      case "USER_INTERACTION_NONE": self = .`none`
      case "USER_INTERACTION_REQUIRED": self = .`required`
      case "USER_INTERACTION_PASSIVE": self = .passive
      case "USER_INTERACTION_ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UserInteraction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .`required`
      case 3: self = .passive
      case 4: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("USER_INTERACTION_UNSPECIFIED")
      case .`none`: return try container.encode("USER_INTERACTION_NONE")
      case .`required`: return try container.encode("USER_INTERACTION_REQUIRED")
      case .passive: return try container.encode("USER_INTERACTION_PASSIVE")
      case .active: return try container.encode("USER_INTERACTION_ACTIVE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Scope.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Scope: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Scope: Unchanged (S:U). Defined in CVSS v3.
    case unchanged
    /// Scope: Changed (S:C). Defined in CVSS v3.
    case changed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unchanged: return 1
      case .changed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SCOPE_UNSPECIFIED"
      case .unchanged: return "SCOPE_UNCHANGED"
      case .changed: return "SCOPE_CHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Scope/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SCOPE_UNSPECIFIED": self = .unspecified
      case "SCOPE_UNCHANGED": self = .unchanged
      case "SCOPE_CHANGED": self = .changed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Scope/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unchanged
      case 2: self = .changed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SCOPE_UNSPECIFIED")
      case .unchanged: return try container.encode("SCOPE_UNCHANGED")
      case .changed: return try container.encode("SCOPE_CHANGED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Impact.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Impact: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// High impact (H). Defined in CVSS v3, v4.
    case high
    /// Low impact (L). Defined in CVSS v3, v4.
    case low
    /// No impact (N). Defined in CVSS v2, v3, v4.
    case `none`
    /// Partial impact (P). Defined in CVSS v2.
    case partial
    /// Complete impact (C). Defined in CVSS v2.
    case complete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .high: return 1
      case .low: return 2
      case .`none`: return 3
      case .partial: return 4
      case .complete: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IMPACT_UNSPECIFIED"
      case .high: return "IMPACT_HIGH"
      case .low: return "IMPACT_LOW"
      case .`none`: return "IMPACT_NONE"
      case .partial: return "IMPACT_PARTIAL"
      case .complete: return "IMPACT_COMPLETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Impact/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IMPACT_UNSPECIFIED": self = .unspecified
      case "IMPACT_HIGH": self = .high
      case "IMPACT_LOW": self = .low
      case "IMPACT_NONE": self = .`none`
      case "IMPACT_PARTIAL": self = .partial
      case "IMPACT_COMPLETE": self = .complete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Impact/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .high
      case 2: self = .low
      case 3: self = .`none`
      case 4: self = .partial
      case 5: self = .complete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("IMPACT_UNSPECIFIED")
      case .high: return try container.encode("IMPACT_HIGH")
      case .low: return try container.encode("IMPACT_LOW")
      case .`none`: return try container.encode("IMPACT_NONE")
      case .partial: return try container.encode("IMPACT_PARTIAL")
      case .complete: return try container.encode("IMPACT_COMPLETE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Attack Requirements.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AttackRequirements: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// No attack requirements (AT:N). Defined in CVSS v4.
    case `none`
    /// Attack requirements: Present (AT:P). Defined in CVSS v4.
    case present
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .present: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ATTACK_REQUIREMENTS_UNSPECIFIED"
      case .`none`: return "ATTACK_REQUIREMENTS_NONE"
      case .present: return "ATTACK_REQUIREMENTS_PRESENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AttackRequirements/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ATTACK_REQUIREMENTS_UNSPECIFIED": self = .unspecified
      case "ATTACK_REQUIREMENTS_NONE": self = .`none`
      case "ATTACK_REQUIREMENTS_PRESENT": self = .present
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AttackRequirements/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .present
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ATTACK_REQUIREMENTS_UNSPECIFIED")
      case .`none`: return try container.encode("ATTACK_REQUIREMENTS_NONE")
      case .present: return try container.encode("ATTACK_REQUIREMENTS_PRESENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Exploit Maturity (E). Defined in CVSS v4.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ExploitMaturity: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Exploit maturity: Not defined (E:X). Defined in CVSS v4.
    case notDefined
    /// Exploit maturity: Attacked (E:A). Defined in CVSS v4.
    case attacked
    /// Exploit maturity: Proof-of-concept (E:P). Defined in CVSS v4.
    case poc
    /// Exploit maturity: Unreported (E:U). Defined in CVSS v4.
    case unreported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notDefined: return 1
      case .attacked: return 2
      case .poc: return 3
      case .unreported: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXPLOIT_MATURITY_UNSPECIFIED"
      case .notDefined: return "EXPLOIT_MATURITY_NOT_DEFINED"
      case .attacked: return "EXPLOIT_MATURITY_ATTACKED"
      case .poc: return "EXPLOIT_MATURITY_POC"
      case .unreported: return "EXPLOIT_MATURITY_UNREPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExploitMaturity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXPLOIT_MATURITY_UNSPECIFIED": self = .unspecified
      case "EXPLOIT_MATURITY_NOT_DEFINED": self = .notDefined
      case "EXPLOIT_MATURITY_ATTACKED": self = .attacked
      case "EXPLOIT_MATURITY_POC": self = .poc
      case "EXPLOIT_MATURITY_UNREPORTED": self = .unreported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExploitMaturity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notDefined
      case 2: self = .attacked
      case 3: self = .poc
      case 4: self = .unreported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EXPLOIT_MATURITY_UNSPECIFIED")
      case .notDefined: return try container.encode("EXPLOIT_MATURITY_NOT_DEFINED")
      case .attacked: return try container.encode("EXPLOIT_MATURITY_ATTACKED")
      case .poc: return try container.encode("EXPLOIT_MATURITY_POC")
      case .unreported: return try container.encode("EXPLOIT_MATURITY_UNREPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.CVSS"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
