// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Provides information about the analysis status of a discovered resource.
public struct DiscoveryOccurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether the resource is continuously analyzed.
  public var continuousAnalysis: DiscoveryOccurrence.ContinuousAnalysis =
    DiscoveryOccurrence.ContinuousAnalysis()

  /// The status of discovery for the resource.
  public var analysisStatus: DiscoveryOccurrence.AnalysisStatus =
    DiscoveryOccurrence.AnalysisStatus()

  public var analysisCompleted: DiscoveryOccurrence.AnalysisCompleted? = nil

  /// Indicates any errors encountered during analysis of a resource. There
  /// could be 0 or more of these errors.
  public var analysisError: [GoogleRpc.Status] = []

  /// When an error is encountered this will contain a LocalizedMessage under
  /// details to show to the user. The LocalizedMessage is output only and
  /// populated by the API.
  public var analysisStatusError: GoogleRpc.Status? = nil

  /// The CPE of the resource being scanned.
  public var cpe: Swift.String = Swift.String()

  /// The last time this resource was scanned.
  public var lastScanTime: GoogleWKT.WKTTimestamp? = nil

  /// The time occurrences related to this discovery occurrence were archived.
  public var archiveTime: GoogleWKT.WKTTimestamp? = nil

  /// The status of an SBOM generation.
  public var sbomStatus: DiscoveryOccurrence.SBOMStatus? = nil

  /// The status of an vulnerability attestation generation.
  public var vulnerabilityAttestation: DiscoveryOccurrence.VulnerabilityAttestation? = nil

  /// Files that make up the resource described by the occurrence.
  public var files: [DiscoveryOccurrence.File] = []

  /// The last time vulnerability scan results changed.
  public var lastVulnerabilityUpdateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveryOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryOccurrence().with { $0.continuousAnalysis = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let continuousAnalysis = CodingKeys(stringValue: "continuousAnalysis")
    static let analysisStatus = CodingKeys(stringValue: "analysisStatus")
    static let analysisCompleted = CodingKeys(stringValue: "analysisCompleted")
    static let analysisError = CodingKeys(stringValue: "analysisError")
    static let analysisStatusError = CodingKeys(stringValue: "analysisStatusError")
    static let cpe = CodingKeys(stringValue: "cpe")
    static let lastScanTime = CodingKeys(stringValue: "lastScanTime")
    static let archiveTime = CodingKeys(stringValue: "archiveTime")
    static let sbomStatus = CodingKeys(stringValue: "sbomStatus")
    static let vulnerabilityAttestation = CodingKeys(stringValue: "vulnerabilityAttestation")
    static let files = CodingKeys(stringValue: "files")
    static let lastVulnerabilityUpdateTime = CodingKeys(stringValue: "lastVulnerabilityUpdateTime")

    static let _knownKeys: Set<Swift.String> = [
      "continuousAnalysis",
      "analysisStatus",
      "analysisCompleted",
      "analysisError",
      "analysisStatusError",
      "cpe",
      "lastScanTime",
      "archiveTime",
      "sbomStatus",
      "vulnerabilityAttestation",
      "files",
      "lastVulnerabilityUpdateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      DiscoveryOccurrence.ContinuousAnalysis.self, forKey: .continuousAnalysis)
    {
      self.continuousAnalysis = value
    }
    if let value = try container.decodeIfPresent(
      DiscoveryOccurrence.AnalysisStatus.self, forKey: .analysisStatus)
    {
      self.analysisStatus = value
    }
    self.analysisCompleted = try container.decodeIfPresent(
      DiscoveryOccurrence.AnalysisCompleted.self, forKey: .analysisCompleted)
    if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .analysisError) {
      self.analysisError = value
    }
    self.analysisStatusError = try container.decodeIfPresent(
      GoogleRpc.Status.self, forKey: .analysisStatusError)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpe) {
      self.cpe = value
    }
    self.lastScanTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastScanTime)
    self.archiveTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .archiveTime)
    self.sbomStatus = try container.decodeIfPresent(
      DiscoveryOccurrence.SBOMStatus.self, forKey: .sbomStatus)
    self.vulnerabilityAttestation = try container.decodeIfPresent(
      DiscoveryOccurrence.VulnerabilityAttestation.self, forKey: .vulnerabilityAttestation)
    if let value = try container.decodeIfPresent([DiscoveryOccurrence.File].self, forKey: .files) {
      self.files = value
    }
    self.lastVulnerabilityUpdateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastVulnerabilityUpdateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.continuousAnalysis, forKey: .continuousAnalysis)
    try container.encode(self.analysisStatus, forKey: .analysisStatus)
    try container.encodeIfPresent(self.analysisCompleted, forKey: .analysisCompleted)
    try container.encode(self.analysisError, forKey: .analysisError)
    try container.encodeIfPresent(self.analysisStatusError, forKey: .analysisStatusError)
    try container.encode(self.cpe, forKey: .cpe)
    try container.encodeIfPresent(self.lastScanTime, forKey: .lastScanTime)
    try container.encodeIfPresent(self.archiveTime, forKey: .archiveTime)
    try container.encodeIfPresent(self.sbomStatus, forKey: .sbomStatus)
    try container.encodeIfPresent(self.vulnerabilityAttestation, forKey: .vulnerabilityAttestation)
    try container.encode(self.files, forKey: .files)
    try container.encodeIfPresent(
      self.lastVulnerabilityUpdateTime, forKey: .lastVulnerabilityUpdateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates which analysis completed successfully. Multiple types of
  /// analysis can be performed on a single resource.
  public struct AnalysisCompleted: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var analysisType: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AnalysisCompleted`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnalysisCompleted().with { $0.analysisType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let analysisType = CodingKeys(stringValue: "analysisType")

      static let _knownKeys: Set<Swift.String> = [
        "analysisType"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .analysisType) {
        self.analysisType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.analysisType, forKey: .analysisType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.AnalysisCompleted"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The status of an SBOM generation.
  public struct SBOMStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The progress of the SBOM generation.
    public var sbomState: DiscoveryOccurrence.SBOMStatus.SBOMState = DiscoveryOccurrence.SBOMStatus
      .SBOMState()

    /// If there was an error generating an SBOM, this will indicate what that
    /// error was.
    public var error: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SBOMStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SBOMStatus().with { $0.sbomState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sbomState = CodingKeys(stringValue: "sbomState")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "sbomState",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        DiscoveryOccurrence.SBOMStatus.SBOMState.self, forKey: .sbomState)
      {
        self.sbomState = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .error) {
        self.error = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sbomState, forKey: .sbomState)
      try container.encode(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// An enum indicating the progress of the SBOM generation.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SBOMState: Codable, Equatable, Hashable, Sendable {
      /// Default unknown state.
      case unspecified
      /// SBOM scanning is pending.
      case pending
      /// SBOM scanning has completed.
      case complete
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pending: return 1
        case .complete: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SBOM_STATE_UNSPECIFIED"
        case .pending: return "PENDING"
        case .complete: return "COMPLETE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SBOMState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SBOM_STATE_UNSPECIFIED": self = .unspecified
        case "PENDING": self = .pending
        case "COMPLETE": self = .complete
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SBOMState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pending
        case 2: self = .complete
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SBOM_STATE_UNSPECIFIED")
        case .pending: return try container.encode("PENDING")
        case .complete: return try container.encode("COMPLETE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.SBOMStatus"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The status of an vulnerability attestation generation.
  public struct VulnerabilityAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The last time we attempted to generate an attestation.
    public var lastAttemptTime: GoogleWKT.WKTTimestamp? = nil

    /// The success/failure state of the latest attestation attempt.
    public var state: DiscoveryOccurrence.VulnerabilityAttestation.VulnerabilityAttestationState =
      DiscoveryOccurrence.VulnerabilityAttestation.VulnerabilityAttestationState()

    /// If failure, the error reason for why the attestation generation failed.
    public var error: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VulnerabilityAttestation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VulnerabilityAttestation().with { $0.lastAttemptTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let lastAttemptTime = CodingKeys(stringValue: "lastAttemptTime")
      static let state = CodingKeys(stringValue: "state")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "lastAttemptTime",
        "state",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.lastAttemptTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .lastAttemptTime)
      if let value = try container.decodeIfPresent(
        DiscoveryOccurrence.VulnerabilityAttestation.VulnerabilityAttestationState.self,
        forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .error) {
        self.error = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.lastAttemptTime, forKey: .lastAttemptTime)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// An enum indicating the state of the attestation generation.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum VulnerabilityAttestationState: Codable, Equatable, Hashable, Sendable {
      /// Default unknown state.
      case unspecified
      /// Attestation was successfully generated and stored.
      case success
      /// Attestation was unsuccessfully generated and stored.
      case failure
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .success: return 1
        case .failure: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "VULNERABILITY_ATTESTATION_STATE_UNSPECIFIED"
        case .success: return "SUCCESS"
        case .failure: return "FAILURE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VulnerabilityAttestationState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "VULNERABILITY_ATTESTATION_STATE_UNSPECIFIED": self = .unspecified
        case "SUCCESS": self = .success
        case "FAILURE": self = .failure
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VulnerabilityAttestationState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .success
        case 2: self = .failure
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified:
          return try container.encode("VULNERABILITY_ATTESTATION_STATE_UNSPECIFIED")
        case .success: return try container.encode("SUCCESS")
        case .failure: return try container.encode("FAILURE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.VulnerabilityAttestation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct File: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var name: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `File`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = File().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let digest = CodingKeys(stringValue: "digest")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "digest",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .digest)
      {
        self.digest = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.digest, forKey: .digest)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.File"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Whether the resource is continuously analyzed.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ContinuousAnalysis: Codable, Equatable, Hashable, Sendable {
    /// Unknown.
    case unspecified
    /// The resource is continuously analyzed.
    case active
    /// The resource is ignored for continuous analysis.
    case inactive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONTINUOUS_ANALYSIS_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContinuousAnalysis/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONTINUOUS_ANALYSIS_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContinuousAnalysis/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONTINUOUS_ANALYSIS_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .inactive: return try container.encode("INACTIVE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Analysis status for a resource. Currently for initial analysis only (not
  /// updated in continuous analysis).
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AnalysisStatus: Codable, Equatable, Hashable, Sendable {
    /// Unknown.
    case unspecified
    /// Resource is known but no action has been taken yet.
    case pending
    /// Resource is being analyzed.
    case scanning
    /// Analysis has completed.
    case complete
    /// Analysis has finished unsuccessfully, the analysis itself is in a bad
    /// state.
    case finishedFailed
    /// The resource is known not to be supported.
    case finishedUnsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .scanning: return 2
      case .complete: return 3
      case .finishedFailed: return 4
      case .finishedUnsupported: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ANALYSIS_STATUS_UNSPECIFIED"
      case .pending: return "PENDING"
      case .scanning: return "SCANNING"
      case .complete: return "COMPLETE"
      case .finishedFailed: return "FINISHED_FAILED"
      case .finishedUnsupported: return "FINISHED_UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AnalysisStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ANALYSIS_STATUS_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "SCANNING": self = .scanning
      case "FINISHED_SUCCESS": self = .complete
      case "COMPLETE": self = .complete
      case "FINISHED_FAILED": self = .finishedFailed
      case "FINISHED_UNSUPPORTED": self = .finishedUnsupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AnalysisStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .scanning
      case 3: self = .complete
      case 4: self = .finishedFailed
      case 5: self = .finishedUnsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ANALYSIS_STATUS_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .scanning: return try container.encode("SCANNING")
      case .complete: return try container.encode("COMPLETE")
      case .finishedFailed: return try container.encode("FINISHED_FAILED")
      case .finishedUnsupported: return try container.encode("FINISHED_UNSUPPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
