// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MUST match
/// https://github.com/secure-systems-lab/dsse/blob/master/envelope.proto. An
/// authenticated message of arbitrary type.
public struct Envelope: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var payload: Foundation.Data = Foundation.Data()

  public var payloadType: Swift.String = Swift.String()

  public var signatures: [EnvelopeSignature] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Envelope`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Envelope().with { $0.payload = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let payload = CodingKeys(stringValue: "payload")
    static let payloadType = CodingKeys(stringValue: "payloadType")
    static let signatures = CodingKeys(stringValue: "signatures")

    static let _knownKeys: Set<Swift.String> = [
      "payload",
      "payloadType",
      "signatures",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .payload) {
      self.payload = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .payloadType) {
      self.payloadType = value
    }
    if let value = try container.decodeIfPresent([EnvelopeSignature].self, forKey: .signatures) {
      self.signatures = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.payload, forKey: .payload)
    try container.encode(self.payloadType, forKey: .payloadType)
    try container.encode(self.signatures, forKey: .signatures)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Envelope"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
