// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A set of properties that uniquely identify a given Docker image.
public struct Fingerprint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The layer ID of the final layer in the Docker image's v1
  /// representation.
  public var v1Name: Swift.String = Swift.String()

  /// Required. The ordered list of v2 blobs that represent a given image.
  public var v2Blob: [Swift.String] = []

  /// Output only. The name of the image's v2 blobs computed via:
  ///   [bottom] := v2_blob[bottom]
  ///   [N] := sha256(v2_blob[N] + " " + v2_name[N+1])
  /// Only the name of the final blob is kept.
  public var v2Name: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Fingerprint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Fingerprint().with { $0.v1Name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let v1Name = CodingKeys(stringValue: "v1Name")
    static let v2Blob = CodingKeys(stringValue: "v2Blob")
    static let v2Name = CodingKeys(stringValue: "v2Name")

    static let _knownKeys: Set<Swift.String> = [
      "v1Name",
      "v2Blob",
      "v2Name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .v1Name) {
      self.v1Name = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .v2Blob) {
      self.v2Blob = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .v2Name) {
      self.v2Name = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.v1Name, forKey: .v1Name)
    try container.encode(self.v2Blob, forKey: .v2Blob)
    try container.encode(self.v2Name, forKey: .v2Name)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Fingerprint"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
