// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// [Grafeas](https://grafeas.io) API.
///
/// Retrieves analysis results of Cloud components such as Docker container
/// images.
///
/// Analysis results are stored as a series of occurrences. An `Occurrence`
/// contains information about a specific analysis instance on a resource. An
/// occurrence refers to a `Note`. A note contains details describing the
/// analysis and is generally stored in a separate project, called a `Provider`.
/// Multiple occurrences can refer to the same note.
///
/// For example, an SSL vulnerability could affect multiple images. In this case,
/// there would be one note for the vulnerability and an occurrence for each
/// image with the vulnerability referring to that note.
///
/// @Snippet(path: "GrafeasQuickstart")
public final class GrafeasClient: Clients.GrafeasProtocol, Sendable {
  let inner: any Clients.GrafeasStub

  /// Creates a new `GrafeasClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.GrafeasStub = try Clients.GrafeasTransport(options)
    inner = Clients.GrafeasRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.GrafeasLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets the specified occurrence.
  ///
  /// @Snippet(path: "Grafeas_GetOccurrence")
  public func getOccurrence(
    request: GetOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    try await self.inner.getOccurrence(request: request, options: options)
  }

  /// Lists occurrences for the specified project.
  ///
  /// @Snippet(path: "Grafeas_ListOccurrences")
  public func listOccurrences(
    request: ListOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse {
    try await self.inner.listOccurrences(request: request, options: options)
  }

  /// Deletes the specified occurrence. For example, use this method to delete an
  /// occurrence when the occurrence is no longer applicable for the given
  /// resource.
  ///
  /// @Snippet(path: "Grafeas_DeleteOccurrence")
  public func deleteOccurrence(
    request: DeleteOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOccurrence(request: request, options: options)
  }

  /// Creates a new occurrence.
  ///
  /// @Snippet(path: "Grafeas_CreateOccurrence")
  public func createOccurrence(
    request: CreateOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    try await self.inner.createOccurrence(request: request, options: options)
  }

  /// Creates new occurrences in batch.
  ///
  /// @Snippet(path: "Grafeas_BatchCreateOccurrences")
  public func batchCreateOccurrences(
    request: BatchCreateOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
    try await self.inner.batchCreateOccurrences(request: request, options: options)
  }

  /// Updates the specified occurrence.
  ///
  /// @Snippet(path: "Grafeas_UpdateOccurrence")
  public func updateOccurrence(
    request: UpdateOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    try await self.inner.updateOccurrence(request: request, options: options)
  }

  /// Gets the note attached to the specified occurrence. Consumer projects can
  /// use this method to get a note that belongs to a provider project.
  ///
  /// @Snippet(path: "Grafeas_GetOccurrenceNote")
  public func getOccurrenceNote(
    request: GetOccurrenceNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    try await self.inner.getOccurrenceNote(request: request, options: options)
  }

  /// Gets the specified note.
  ///
  /// @Snippet(path: "Grafeas_GetNote")
  public func getNote(
    request: GetNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    try await self.inner.getNote(request: request, options: options)
  }

  /// Lists notes for the specified project.
  ///
  /// @Snippet(path: "Grafeas_ListNotes")
  public func listNotes(
    request: ListNotesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListNotesResponse {
    try await self.inner.listNotes(request: request, options: options)
  }

  /// Deletes the specified note.
  ///
  /// @Snippet(path: "Grafeas_DeleteNote")
  public func deleteNote(
    request: DeleteNoteRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteNote(request: request, options: options)
  }

  /// Creates a new note.
  ///
  /// @Snippet(path: "Grafeas_CreateNote")
  public func createNote(
    request: CreateNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    try await self.inner.createNote(request: request, options: options)
  }

  /// Creates new notes in batch.
  ///
  /// @Snippet(path: "Grafeas_BatchCreateNotes")
  public func batchCreateNotes(
    request: BatchCreateNotesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
    try await self.inner.batchCreateNotes(request: request, options: options)
  }

  /// Updates the specified note.
  ///
  /// @Snippet(path: "Grafeas_UpdateNote")
  public func updateNote(
    request: UpdateNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    try await self.inner.updateNote(request: request, options: options)
  }

  /// Lists occurrences referencing the specified note. Provider projects can use
  /// this method to get all occurrences across consumer projects referencing the
  /// specified note.
  ///
  /// @Snippet(path: "Grafeas_ListNoteOccurrences")
  public func listNoteOccurrences(
    request: ListNoteOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse {
    try await self.inner.listNoteOccurrences(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `GrafeasClient`.
  ///
  /// To mock `GrafeasClient` change your functions to receive
  /// `some GrafeasProtocol` or `any GrafeasProtocol`
  /// and pass a mock implementation in your tests.
  public protocol GrafeasProtocol: Sendable {
    /// See `GrafeasClient.getOccurrence`.
    func getOccurrence(
      request: GetOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    /// See `GrafeasClient.listOccurrences`.
    func listOccurrences(
      request: ListOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse

    /// See `GrafeasClient.deleteOccurrence`.
    func deleteOccurrence(
      request: DeleteOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `GrafeasClient.createOccurrence`.
    func createOccurrence(
      request: CreateOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    /// See `GrafeasClient.batchCreateOccurrences`.
    func batchCreateOccurrences(
      request: BatchCreateOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse

    /// See `GrafeasClient.updateOccurrence`.
    func updateOccurrence(
      request: UpdateOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    /// See `GrafeasClient.getOccurrenceNote`.
    func getOccurrenceNote(
      request: GetOccurrenceNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    /// See `GrafeasClient.getNote`.
    func getNote(
      request: GetNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    /// See `GrafeasClient.listNotes`.
    func listNotes(
      request: ListNotesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNotesResponse

    /// See `GrafeasClient.deleteNote`.
    func deleteNote(
      request: DeleteNoteRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `GrafeasClient.createNote`.
    func createNote(
      request: CreateNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    /// See `GrafeasClient.batchCreateNotes`.
    func batchCreateNotes(
      request: BatchCreateNotesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse

    /// See `GrafeasClient.updateNote`.
    func updateNote(
      request: UpdateNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    /// See `GrafeasClient.listNoteOccurrences`.
    func listNoteOccurrences(
      request: ListNoteOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse
  }
}

// Default implementations
extension Clients.GrafeasProtocol {
  public func getOccurrence(request: GetOccurrenceRequest) async throws
    -> GoogleGrafeasV1.Occurrence
  {
    try await self.getOccurrence(request: request, options: .init())
  }

  public func getOccurrence(
    request: GetOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOccurrence(
    name: Swift.String,
  ) async throws -> GoogleGrafeasV1.Occurrence {
    let request = GetOccurrenceRequest().with {
      $0.name = name
    }
    return try await self.getOccurrence(request: request)
  }

  public func listOccurrences(request: ListOccurrencesRequest) async throws
    -> GoogleGrafeasV1.ListOccurrencesResponse
  {
    try await self.listOccurrences(request: request, options: .init())
  }

  public func listOccurrences(
    request: ListOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOccurrencesByItems(
    request: ListOccurrencesRequest
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    self.listOccurrencesByItems(request: request, options: .init())
  }

  /// Lists occurrences for the specified project.
  ///
  /// @Snippet(path: "Grafeas_ListOccurrences")
  public func listOccurrencesByItems(
    request: ListOccurrencesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleGrafeasV1.ListOccurrencesResponse in
      var request = request
      request.pageToken = token
      return try await self.listOccurrences(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOccurrencesByItems(
    parent: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    let request = ListOccurrencesRequest().with {
      $0.parent = parent
      $0.filter = filter
    }
    return self.listOccurrencesByItems(request: request)
  }

  public func deleteOccurrence(request: DeleteOccurrenceRequest) async throws {
    try await self.deleteOccurrence(request: request, options: .init())
  }

  public func deleteOccurrence(
    request: DeleteOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOccurrence(
    name: Swift.String,
  ) async throws {
    let request = DeleteOccurrenceRequest().with {
      $0.name = name
    }
    try await self.deleteOccurrence(request: request)
  }

  public func createOccurrence(request: CreateOccurrenceRequest) async throws
    -> GoogleGrafeasV1.Occurrence
  {
    try await self.createOccurrence(request: request, options: .init())
  }

  public func createOccurrence(
    request: CreateOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createOccurrence(
    parent: Swift.String,
    occurrence: Occurrence?,
  ) async throws -> GoogleGrafeasV1.Occurrence {
    let request = CreateOccurrenceRequest().with {
      $0.parent = parent
      $0.occurrence = occurrence
    }
    return try await self.createOccurrence(request: request)
  }

  public func batchCreateOccurrences(request: BatchCreateOccurrencesRequest) async throws
    -> GoogleGrafeasV1.BatchCreateOccurrencesResponse
  {
    try await self.batchCreateOccurrences(request: request, options: .init())
  }

  public func batchCreateOccurrences(
    request: BatchCreateOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchCreateOccurrences(
    parent: Swift.String,
    occurrences: [Occurrence],
  ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
    let request = BatchCreateOccurrencesRequest().with {
      $0.parent = parent
      $0.occurrences = occurrences
    }
    return try await self.batchCreateOccurrences(request: request)
  }

  public func updateOccurrence(request: UpdateOccurrenceRequest) async throws
    -> GoogleGrafeasV1.Occurrence
  {
    try await self.updateOccurrence(request: request, options: .init())
  }

  public func updateOccurrence(
    request: UpdateOccurrenceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Occurrence {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateOccurrence(
    name: Swift.String,
    occurrence: Occurrence?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleGrafeasV1.Occurrence {
    let request = UpdateOccurrenceRequest().with {
      $0.name = name
      $0.occurrence = occurrence
      $0.updateMask = updateMask
    }
    return try await self.updateOccurrence(request: request)
  }

  public func getOccurrenceNote(request: GetOccurrenceNoteRequest) async throws
    -> GoogleGrafeasV1.Note
  {
    try await self.getOccurrenceNote(request: request, options: .init())
  }

  public func getOccurrenceNote(
    request: GetOccurrenceNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOccurrenceNote(
    name: Swift.String,
  ) async throws -> GoogleGrafeasV1.Note {
    let request = GetOccurrenceNoteRequest().with {
      $0.name = name
    }
    return try await self.getOccurrenceNote(request: request)
  }

  public func getNote(request: GetNoteRequest) async throws -> GoogleGrafeasV1.Note {
    try await self.getNote(request: request, options: .init())
  }

  public func getNote(
    request: GetNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getNote(
    name: Swift.String,
  ) async throws -> GoogleGrafeasV1.Note {
    let request = GetNoteRequest().with {
      $0.name = name
    }
    return try await self.getNote(request: request)
  }

  public func listNotes(request: ListNotesRequest) async throws -> GoogleGrafeasV1.ListNotesResponse
  {
    try await self.listNotes(request: request, options: .init())
  }

  public func listNotes(
    request: ListNotesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListNotesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listNotesByItems(
    request: ListNotesRequest
  ) -> any AsyncSequence<Note, Swift.Error> & Sendable {
    self.listNotesByItems(request: request, options: .init())
  }

  /// Lists notes for the specified project.
  ///
  /// @Snippet(path: "Grafeas_ListNotes")
  public func listNotesByItems(
    request: ListNotesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Note, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleGrafeasV1.ListNotesResponse in
      var request = request
      request.pageToken = token
      return try await self.listNotes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNotesByItems(
    parent: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<Note, Swift.Error> & Sendable {
    let request = ListNotesRequest().with {
      $0.parent = parent
      $0.filter = filter
    }
    return self.listNotesByItems(request: request)
  }

  public func deleteNote(request: DeleteNoteRequest) async throws {
    try await self.deleteNote(request: request, options: .init())
  }

  public func deleteNote(
    request: DeleteNoteRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteNote(
    name: Swift.String,
  ) async throws {
    let request = DeleteNoteRequest().with {
      $0.name = name
    }
    try await self.deleteNote(request: request)
  }

  public func createNote(request: CreateNoteRequest) async throws -> GoogleGrafeasV1.Note {
    try await self.createNote(request: request, options: .init())
  }

  public func createNote(
    request: CreateNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createNote(
    parent: Swift.String,
    noteId: Swift.String,
    note: Note?,
  ) async throws -> GoogleGrafeasV1.Note {
    let request = CreateNoteRequest().with {
      $0.parent = parent
      $0.noteId = noteId
      $0.note = note
    }
    return try await self.createNote(request: request)
  }

  public func batchCreateNotes(request: BatchCreateNotesRequest) async throws
    -> GoogleGrafeasV1.BatchCreateNotesResponse
  {
    try await self.batchCreateNotes(request: request, options: .init())
  }

  public func batchCreateNotes(
    request: BatchCreateNotesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchCreateNotes(
    parent: Swift.String,
    notes: [Swift.String: Note],
  ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
    let request = BatchCreateNotesRequest().with {
      $0.parent = parent
      $0.notes = notes
    }
    return try await self.batchCreateNotes(request: request)
  }

  public func updateNote(request: UpdateNoteRequest) async throws -> GoogleGrafeasV1.Note {
    try await self.updateNote(request: request, options: .init())
  }

  public func updateNote(
    request: UpdateNoteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.Note {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateNote(
    name: Swift.String,
    note: Note?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleGrafeasV1.Note {
    let request = UpdateNoteRequest().with {
      $0.name = name
      $0.note = note
      $0.updateMask = updateMask
    }
    return try await self.updateNote(request: request)
  }

  public func listNoteOccurrences(request: ListNoteOccurrencesRequest) async throws
    -> GoogleGrafeasV1.ListNoteOccurrencesResponse
  {
    try await self.listNoteOccurrences(request: request, options: .init())
  }

  public func listNoteOccurrences(
    request: ListNoteOccurrencesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listNoteOccurrencesByItems(
    request: ListNoteOccurrencesRequest
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    self.listNoteOccurrencesByItems(request: request, options: .init())
  }

  /// Lists occurrences referencing the specified note. Provider projects can use
  /// this method to get all occurrences across consumer projects referencing the
  /// specified note.
  ///
  /// @Snippet(path: "Grafeas_ListNoteOccurrences")
  public func listNoteOccurrencesByItems(
    request: ListNoteOccurrencesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse in
      var request = request
      request.pageToken = token
      return try await self.listNoteOccurrences(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNoteOccurrencesByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<Occurrence, Swift.Error> & Sendable {
    let request = ListNoteOccurrencesRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listNoteOccurrencesByItems(request: request)
  }
}
