// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details of the derived image portion of the DockerImage relationship. This
/// image would be produced from a Dockerfile with FROM <DockerImage.Basis in
/// attached Note>.
public struct ImageOccurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The fingerprint of the derived image.
  public var fingerprint: Fingerprint? = nil

  /// Output only. The number of layers by which this image differs from the
  /// associated image basis.
  public var distance: Swift.Int32 = Swift.Int32()

  /// This contains layer-specific metadata, if populated it has length
  /// "distance" and is ordered with [distance] being the layer immediately
  /// following the base image and [1] being the final layer.
  public var layerInfo: [Layer] = []

  /// Output only. This contains the base image URL for the derived image
  /// occurrence.
  public var baseResourceUrl: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageOccurrence().with { $0.fingerprint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fingerprint = CodingKeys(stringValue: "fingerprint")
    static let distance = CodingKeys(stringValue: "distance")
    static let layerInfo = CodingKeys(stringValue: "layerInfo")
    static let baseResourceUrl = CodingKeys(stringValue: "baseResourceUrl")

    static let _knownKeys: Set<Swift.String> = [
      "fingerprint",
      "distance",
      "layerInfo",
      "baseResourceUrl",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.fingerprint = try container.decodeIfPresent(Fingerprint.self, forKey: .fingerprint)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .distance) {
      self.distance = value
    }
    if let value = try container.decodeIfPresent([Layer].self, forKey: .layerInfo) {
      self.layerInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .baseResourceUrl) {
      self.baseResourceUrl = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.fingerprint, forKey: .fingerprint)
    try container.encode(self.distance, forKey: .distance)
    try container.encode(self.layerInfo, forKey: .layerInfo)
    try container.encode(self.baseResourceUrl, forKey: .baseResourceUrl)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.ImageOccurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
