// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct InTotoProvenance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var builderConfig: BuilderConfig? = nil

  /// Identifies the configuration used for the build.
  /// When combined with materials, this SHOULD fully describe the build,
  /// such that re-running this recipe results in bit-for-bit identical output
  /// (if the build is reproducible).
  public var recipe: Recipe? = nil

  public var metadata: Metadata? = nil

  /// The collection of artifacts that influenced the build including sources,
  /// dependencies, build tools, base images, and so on. This is considered to be
  /// incomplete unless metadata.completeness.materials is true. Unset or null is
  /// equivalent to empty.
  public var materials: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InTotoProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InTotoProvenance().with { $0.builderConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let builderConfig = CodingKeys(stringValue: "builderConfig")
    static let recipe = CodingKeys(stringValue: "recipe")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let materials = CodingKeys(stringValue: "materials")

    static let _knownKeys: Set<Swift.String> = [
      "builderConfig",
      "recipe",
      "metadata",
      "materials",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.builderConfig = try container.decodeIfPresent(BuilderConfig.self, forKey: .builderConfig)
    self.recipe = try container.decodeIfPresent(Recipe.self, forKey: .recipe)
    self.metadata = try container.decodeIfPresent(Metadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .materials) {
      self.materials = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.builderConfig, forKey: .builderConfig)
    try container.encodeIfPresent(self.recipe, forKey: .recipe)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.materials, forKey: .materials)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.InTotoProvenance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
