// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct InTotoSlsaProvenanceV1: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// InToto spec defined at
  /// https://github.com/in-toto/attestation/tree/main/spec#statement
  public var type: Swift.String = Swift.String()

  public var subject: [Subject] = []

  public var predicateType: Swift.String = Swift.String()

  public var predicate: InTotoSlsaProvenanceV1.SlsaProvenanceV1? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InTotoSlsaProvenanceV1`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InTotoSlsaProvenanceV1().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "_type")
    static let subject = CodingKeys(stringValue: "subject")
    static let predicateType = CodingKeys(stringValue: "predicateType")
    static let predicate = CodingKeys(stringValue: "predicate")

    static let _knownKeys: Set<Swift.String> = [
      "_type",
      "subject",
      "predicateType",
      "predicate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent([Subject].self, forKey: .subject) {
      self.subject = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .predicateType) {
      self.predicateType = value
    }
    self.predicate = try container.decodeIfPresent(
      InTotoSlsaProvenanceV1.SlsaProvenanceV1.self, forKey: .predicate)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.predicateType, forKey: .predicateType)
    try container.encodeIfPresent(self.predicate, forKey: .predicate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Keep in sync with schema at
  /// https://github.com/slsa-framework/slsa/blob/main/docs/provenance/schema/v1/provenance.proto
  /// Builder renamed to ProvenanceBuilder because of Java conflicts.
  public struct SlsaProvenanceV1: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var buildDefinition: InTotoSlsaProvenanceV1.BuildDefinition? = nil

    public var runDetails: InTotoSlsaProvenanceV1.RunDetails? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaProvenanceV1`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaProvenanceV1().with { $0.buildDefinition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let buildDefinition = CodingKeys(stringValue: "buildDefinition")
      static let runDetails = CodingKeys(stringValue: "runDetails")

      static let _knownKeys: Set<Swift.String> = [
        "buildDefinition",
        "runDetails",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.buildDefinition = try container.decodeIfPresent(
        InTotoSlsaProvenanceV1.BuildDefinition.self, forKey: .buildDefinition)
      self.runDetails = try container.decodeIfPresent(
        InTotoSlsaProvenanceV1.RunDetails.self, forKey: .runDetails)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.buildDefinition, forKey: .buildDefinition)
      try container.encodeIfPresent(self.runDetails, forKey: .runDetails)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.SlsaProvenanceV1"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct BuildDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var buildType: Swift.String = Swift.String()

    public var externalParameters: GoogleWKT.WKTStruct? = nil

    public var internalParameters: GoogleWKT.WKTStruct? = nil

    public var resolvedDependencies: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BuildDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildDefinition().with { $0.buildType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let buildType = CodingKeys(stringValue: "buildType")
      static let externalParameters = CodingKeys(stringValue: "externalParameters")
      static let internalParameters = CodingKeys(stringValue: "internalParameters")
      static let resolvedDependencies = CodingKeys(stringValue: "resolvedDependencies")

      static let _knownKeys: Set<Swift.String> = [
        "buildType",
        "externalParameters",
        "internalParameters",
        "resolvedDependencies",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .buildType) {
        self.buildType = value
      }
      self.externalParameters = try container.decodeIfPresent(
        GoogleWKT.WKTStruct.self, forKey: .externalParameters)
      self.internalParameters = try container.decodeIfPresent(
        GoogleWKT.WKTStruct.self, forKey: .internalParameters)
      if let value = try container.decodeIfPresent(
        [InTotoSlsaProvenanceV1.ResourceDescriptor].self, forKey: .resolvedDependencies)
      {
        self.resolvedDependencies = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.buildType, forKey: .buildType)
      try container.encodeIfPresent(self.externalParameters, forKey: .externalParameters)
      try container.encodeIfPresent(self.internalParameters, forKey: .internalParameters)
      try container.encode(self.resolvedDependencies, forKey: .resolvedDependencies)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.BuildDefinition"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct ResourceDescriptor: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var name: Swift.String = Swift.String()

    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    public var content: Foundation.Data = Foundation.Data()

    public var downloadLocation: Swift.String = Swift.String()

    public var mediaType: Swift.String = Swift.String()

    public var annotations: [Swift.String: GoogleWKT.WKTValue] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ResourceDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceDescriptor().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let uri = CodingKeys(stringValue: "uri")
      static let digest = CodingKeys(stringValue: "digest")
      static let content = CodingKeys(stringValue: "content")
      static let downloadLocation = CodingKeys(stringValue: "downloadLocation")
      static let mediaType = CodingKeys(stringValue: "mediaType")
      static let annotations = CodingKeys(stringValue: "annotations")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "uri",
        "digest",
        "content",
        "downloadLocation",
        "mediaType",
        "annotations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .digest)
      {
        self.digest = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .content) {
        self.content = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .downloadLocation) {
        self.downloadLocation = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mediaType) {
        self.mediaType = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: GoogleWKT.WKTValue].self, forKey: .annotations)
      {
        self.annotations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.uri, forKey: .uri)
      try container.encode(self.digest, forKey: .digest)
      try container.encode(self.content, forKey: .content)
      try container.encode(self.downloadLocation, forKey: .downloadLocation)
      try container.encode(self.mediaType, forKey: .mediaType)
      try container.encode(self.annotations, forKey: .annotations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.ResourceDescriptor"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct RunDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var builder: InTotoSlsaProvenanceV1.ProvenanceBuilder? = nil

    public var metadata: InTotoSlsaProvenanceV1.BuildMetadata? = nil

    public var byproducts: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RunDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RunDetails().with { $0.builder = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let builder = CodingKeys(stringValue: "builder")
      static let metadata = CodingKeys(stringValue: "metadata")
      static let byproducts = CodingKeys(stringValue: "byproducts")

      static let _knownKeys: Set<Swift.String> = [
        "builder",
        "metadata",
        "byproducts",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.builder = try container.decodeIfPresent(
        InTotoSlsaProvenanceV1.ProvenanceBuilder.self, forKey: .builder)
      self.metadata = try container.decodeIfPresent(
        InTotoSlsaProvenanceV1.BuildMetadata.self, forKey: .metadata)
      if let value = try container.decodeIfPresent(
        [InTotoSlsaProvenanceV1.ResourceDescriptor].self, forKey: .byproducts)
      {
        self.byproducts = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.builder, forKey: .builder)
      try container.encodeIfPresent(self.metadata, forKey: .metadata)
      try container.encode(self.byproducts, forKey: .byproducts)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.RunDetails"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct ProvenanceBuilder: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var id: Swift.String = Swift.String()

    public var version: [Swift.String: Swift.String] = [:]

    public var builderDependencies: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProvenanceBuilder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProvenanceBuilder().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let version = CodingKeys(stringValue: "version")
      static let builderDependencies = CodingKeys(stringValue: "builderDependencies")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "version",
        "builderDependencies",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .version)
      {
        self.version = value
      }
      if let value = try container.decodeIfPresent(
        [InTotoSlsaProvenanceV1.ResourceDescriptor].self, forKey: .builderDependencies)
      {
        self.builderDependencies = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.version, forKey: .version)
      try container.encode(self.builderDependencies, forKey: .builderDependencies)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.ProvenanceBuilder"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public struct BuildMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var invocationId: Swift.String = Swift.String()

    public var startedOn: GoogleWKT.WKTTimestamp? = nil

    public var finishedOn: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BuildMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildMetadata().with { $0.invocationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let invocationId = CodingKeys(stringValue: "invocationId")
      static let startedOn = CodingKeys(stringValue: "startedOn")
      static let finishedOn = CodingKeys(stringValue: "finishedOn")

      static let _knownKeys: Set<Swift.String> = [
        "invocationId",
        "startedOn",
        "finishedOn",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .invocationId) {
        self.invocationId = value
      }
      self.startedOn = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startedOn)
      self.finishedOn = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .finishedOn)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.invocationId, forKey: .invocationId)
      try container.encodeIfPresent(self.startedOn, forKey: .startedOn)
      try container.encodeIfPresent(self.finishedOn, forKey: .finishedOn)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.BuildMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
