// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Kind represents the kinds of notes supported.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum NoteKind: Codable, Equatable, Hashable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// The note and occurrence represent a package vulnerability.
  case vulnerability
  /// The note and occurrence assert build provenance.
  case build
  /// This represents an image basis relationship.
  case image
  /// This represents a package installed via a package manager.
  case `package`
  /// The note and occurrence track deployment events.
  case deployment
  /// The note and occurrence track the initial discovery status of a resource.
  case discovery
  /// This represents a logical "role" that can attest to artifacts.
  case attestation
  /// This represents an available package upgrade.
  case upgrade
  /// This represents a Compliance Note
  case compliance
  /// This represents a DSSE attestation Note
  case dsseAttestation
  /// This represents a Vulnerability Assessment.
  case vulnerabilityAssessment
  /// This represents an SBOM Reference.
  case sbomReference
  /// This represents a secret.
  case secret
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .vulnerability: return 1
    case .build: return 2
    case .image: return 3
    case .`package`: return 4
    case .deployment: return 5
    case .discovery: return 6
    case .attestation: return 7
    case .upgrade: return 8
    case .compliance: return 9
    case .dsseAttestation: return 10
    case .vulnerabilityAssessment: return 11
    case .sbomReference: return 12
    case .secret: return 13
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "NOTE_KIND_UNSPECIFIED"
    case .vulnerability: return "VULNERABILITY"
    case .build: return "BUILD"
    case .image: return "IMAGE"
    case .`package`: return "PACKAGE"
    case .deployment: return "DEPLOYMENT"
    case .discovery: return "DISCOVERY"
    case .attestation: return "ATTESTATION"
    case .upgrade: return "UPGRADE"
    case .compliance: return "COMPLIANCE"
    case .dsseAttestation: return "DSSE_ATTESTATION"
    case .vulnerabilityAssessment: return "VULNERABILITY_ASSESSMENT"
    case .sbomReference: return "SBOM_REFERENCE"
    case .secret: return "SECRET"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NoteKind/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "NOTE_KIND_UNSPECIFIED": self = .unspecified
    case "VULNERABILITY": self = .vulnerability
    case "BUILD": self = .build
    case "IMAGE": self = .image
    case "PACKAGE": self = .`package`
    case "DEPLOYMENT": self = .deployment
    case "DISCOVERY": self = .discovery
    case "ATTESTATION": self = .attestation
    case "UPGRADE": self = .upgrade
    case "COMPLIANCE": self = .compliance
    case "DSSE_ATTESTATION": self = .dsseAttestation
    case "VULNERABILITY_ASSESSMENT": self = .vulnerabilityAssessment
    case "SBOM_REFERENCE": self = .sbomReference
    case "SECRET": self = .secret
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NoteKind/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .vulnerability
    case 2: self = .build
    case 3: self = .image
    case 4: self = .`package`
    case 5: self = .deployment
    case 6: self = .discovery
    case 7: self = .attestation
    case 8: self = .upgrade
    case 9: self = .compliance
    case 10: self = .dsseAttestation
    case 11: self = .vulnerabilityAssessment
    case 12: self = .sbomReference
    case 13: self = .secret
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("NOTE_KIND_UNSPECIFIED")
    case .vulnerability: return try container.encode("VULNERABILITY")
    case .build: return try container.encode("BUILD")
    case .image: return try container.encode("IMAGE")
    case .`package`: return try container.encode("PACKAGE")
    case .deployment: return try container.encode("DEPLOYMENT")
    case .discovery: return try container.encode("DISCOVERY")
    case .attestation: return try container.encode("ATTESTATION")
    case .upgrade: return try container.encode("UPGRADE")
    case .compliance: return try container.encode("COMPLIANCE")
    case .dsseAttestation: return try container.encode("DSSE_ATTESTATION")
    case .vulnerabilityAssessment: return try container.encode("VULNERABILITY_ASSESSMENT")
    case .sbomReference: return try container.encode("SBOM_REFERENCE")
    case .secret: return try container.encode("SECRET")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
