// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An instance of an analysis type that has been found on a resource.
public struct Occurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the occurrence in the form of
  /// `projects/[PROJECT_ID]/occurrences/[OCCURRENCE_ID]`.
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. A URI that represents the resource for which the
  /// occurrence applies. For example,
  /// `https://gcr.io/project/image@sha256:123abc` for a Docker image.
  public var resourceUri: Swift.String = Swift.String()

  /// Required. Immutable. The analysis note associated with this occurrence, in
  /// the form of `projects/[PROVIDER_ID]/notes/[NOTE_ID]`. This field can be
  /// used as a filter in list requests.
  public var noteName: Swift.String = Swift.String()

  /// Output only. This explicitly denotes which of the occurrence details are
  /// specified. This field can be used as a filter in list requests.
  public var kind: NoteKind = NoteKind()

  /// A description of actions that can be taken to remedy the note.
  public var remediation: Swift.String = Swift.String()

  /// Output only. The time this occurrence was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time this occurrence was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// https://github.com/secure-systems-lab/dsse
  public var envelope: Envelope? = nil

  /// Required. Immutable. Describes the details of the note kind found on this
  /// resource.
  public var details: OneOf_Details? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Occurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Occurrence().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resourceUri = CodingKeys(stringValue: "resourceUri")
    static let noteName = CodingKeys(stringValue: "noteName")
    static let kind = CodingKeys(stringValue: "kind")
    static let remediation = CodingKeys(stringValue: "remediation")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let vulnerability = CodingKeys(stringValue: "vulnerability")
    static let build = CodingKeys(stringValue: "build")
    static let image = CodingKeys(stringValue: "image")
    static let `package` = CodingKeys(stringValue: "package")
    static let deployment = CodingKeys(stringValue: "deployment")
    static let discovery = CodingKeys(stringValue: "discovery")
    static let attestation = CodingKeys(stringValue: "attestation")
    static let upgrade = CodingKeys(stringValue: "upgrade")
    static let compliance = CodingKeys(stringValue: "compliance")
    static let dsseAttestation = CodingKeys(stringValue: "dsseAttestation")
    static let sbomReference = CodingKeys(stringValue: "sbomReference")
    static let secret = CodingKeys(stringValue: "secret")
    static let envelope = CodingKeys(stringValue: "envelope")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resourceUri",
      "noteName",
      "kind",
      "remediation",
      "createTime",
      "updateTime",
      "vulnerability",
      "build",
      "image",
      "package",
      "deployment",
      "discovery",
      "attestation",
      "upgrade",
      "compliance",
      "dsseAttestation",
      "sbomReference",
      "secret",
      "envelope",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceUri) {
      self.resourceUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .noteName) {
      self.noteName = value
    }
    if let value = try container.decodeIfPresent(NoteKind.self, forKey: .kind) {
      self.kind = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remediation) {
      self.remediation = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.envelope = try container.decodeIfPresent(Envelope.self, forKey: .envelope)

    var details: OneOf_Details? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let vulnerability = try container.decodeIfPresent(
      VulnerabilityOccurrence?.self, forKey: .vulnerability)
    {
      try detailsCheckAndSet(.vulnerability(vulnerability))
    }
    if let build = try container.decodeIfPresent(BuildOccurrence?.self, forKey: .build) {
      try detailsCheckAndSet(.build(build))
    }
    if let image = try container.decodeIfPresent(ImageOccurrence?.self, forKey: .image) {
      try detailsCheckAndSet(.image(image))
    }
    if let `package` = try container.decodeIfPresent(PackageOccurrence?.self, forKey: .`package`) {
      try detailsCheckAndSet(.`package`(`package`))
    }
    if let deployment = try container.decodeIfPresent(
      DeploymentOccurrence?.self, forKey: .deployment)
    {
      try detailsCheckAndSet(.deployment(deployment))
    }
    if let discovery = try container.decodeIfPresent(DiscoveryOccurrence?.self, forKey: .discovery)
    {
      try detailsCheckAndSet(.discovery(discovery))
    }
    if let attestation = try container.decodeIfPresent(
      AttestationOccurrence?.self, forKey: .attestation)
    {
      try detailsCheckAndSet(.attestation(attestation))
    }
    if let upgrade = try container.decodeIfPresent(UpgradeOccurrence?.self, forKey: .upgrade) {
      try detailsCheckAndSet(.upgrade(upgrade))
    }
    if let compliance = try container.decodeIfPresent(
      ComplianceOccurrence?.self, forKey: .compliance)
    {
      try detailsCheckAndSet(.compliance(compliance))
    }
    if let dsseAttestation = try container.decodeIfPresent(
      DSSEAttestationOccurrence?.self, forKey: .dsseAttestation)
    {
      try detailsCheckAndSet(.dsseAttestation(dsseAttestation))
    }
    if let sbomReference = try container.decodeIfPresent(
      SBOMReferenceOccurrence?.self, forKey: .sbomReference)
    {
      try detailsCheckAndSet(.sbomReference(sbomReference))
    }
    if let secret = try container.decodeIfPresent(SecretOccurrence?.self, forKey: .secret) {
      try detailsCheckAndSet(.secret(secret))
    }
    self.details = details
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resourceUri, forKey: .resourceUri)
    try container.encode(self.noteName, forKey: .noteName)
    try container.encode(self.kind, forKey: .kind)
    try container.encode(self.remediation, forKey: .remediation)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.envelope, forKey: .envelope)

    if let choice = self.details {
      switch choice {
      case .vulnerability(let value):
        try container.encode(value, forKey: .vulnerability)
      case .build(let value):
        try container.encode(value, forKey: .build)
      case .image(let value):
        try container.encode(value, forKey: .image)
      case .`package`(let value):
        try container.encode(value, forKey: .`package`)
      case .deployment(let value):
        try container.encode(value, forKey: .deployment)
      case .discovery(let value):
        try container.encode(value, forKey: .discovery)
      case .attestation(let value):
        try container.encode(value, forKey: .attestation)
      case .upgrade(let value):
        try container.encode(value, forKey: .upgrade)
      case .compliance(let value):
        try container.encode(value, forKey: .compliance)
      case .dsseAttestation(let value):
        try container.encode(value, forKey: .dsseAttestation)
      case .sbomReference(let value):
        try container.encode(value, forKey: .sbomReference)
      case .secret(let value):
        try container.encode(value, forKey: .secret)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required. Immutable. Describes the details of the note kind found on this
  /// resource.
  public enum OneOf_Details: Codable, Equatable, Sendable {
    /// Describes a security vulnerability.
    indirect case vulnerability(VulnerabilityOccurrence?)
    /// Describes a verifiable build.
    indirect case build(BuildOccurrence?)
    /// Describes how this resource derives from the basis in the associated
    /// note.
    indirect case image(ImageOccurrence?)
    /// Describes the installation of a package on the linked resource.
    indirect case `package`(PackageOccurrence?)
    /// Describes the deployment of an artifact on a runtime.
    indirect case deployment(DeploymentOccurrence?)
    /// Describes when a resource was discovered.
    indirect case discovery(DiscoveryOccurrence?)
    /// Describes an attestation of an artifact.
    indirect case attestation(AttestationOccurrence?)
    /// Describes an available package upgrade on the linked resource.
    indirect case upgrade(UpgradeOccurrence?)
    /// Describes a compliance violation on a linked resource.
    indirect case compliance(ComplianceOccurrence?)
    /// Describes an attestation of an artifact using dsse.
    indirect case dsseAttestation(DSSEAttestationOccurrence?)
    /// Describes a specific SBOM reference occurrences.
    indirect case sbomReference(SBOMReferenceOccurrence?)
    /// Describes a secret.
    indirect case secret(SecretOccurrence?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Occurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
