// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details on how a particular software package was installed on a system.
public struct PackageOccurrence: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the installed package.
  public var name: Swift.String = Swift.String()

  /// All of the places within the filesystem versions of this package
  /// have been found.
  public var location: [Location] = []

  /// The type of package; whether native or non native (e.g., ruby gems,
  /// node.js packages, etc.).
  public var packageType: Swift.String = Swift.String()

  /// The cpe_uri in [CPE format](https://cpe.mitre.org/specification/)
  /// denoting the package manager version distributing a package.
  /// The cpe_uri will be blank for language packages.
  public var cpeUri: Swift.String = Swift.String()

  /// The CPU architecture for which packages in this distribution channel were
  /// built. Architecture will be blank for language packages.
  public var architecture: Architecture = Architecture()

  /// Licenses that have been declared by the authors of the package.
  public var license: License? = nil

  /// The version of the package.
  public var version: Version? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PackageOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PackageOccurrence().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let location = CodingKeys(stringValue: "location")
    static let packageType = CodingKeys(stringValue: "packageType")
    static let cpeUri = CodingKeys(stringValue: "cpeUri")
    static let architecture = CodingKeys(stringValue: "architecture")
    static let license = CodingKeys(stringValue: "license")
    static let version = CodingKeys(stringValue: "version")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "location",
      "packageType",
      "cpeUri",
      "architecture",
      "license",
      "version",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Location].self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .packageType) {
      self.packageType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpeUri) {
      self.cpeUri = value
    }
    if let value = try container.decodeIfPresent(Architecture.self, forKey: .architecture) {
      self.architecture = value
    }
    self.license = try container.decodeIfPresent(License.self, forKey: .license)
    self.version = try container.decodeIfPresent(Version.self, forKey: .version)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.packageType, forKey: .packageType)
    try container.encode(self.cpeUri, forKey: .cpeUri)
    try container.encode(self.architecture, forKey: .architecture)
    try container.encodeIfPresent(self.license, forKey: .license)
    try container.encodeIfPresent(self.version, forKey: .version)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.PackageOccurrence"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
