// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Steps taken to build the artifact.
/// For a TaskRun, typically each container corresponds to one step in the
/// recipe.
public struct Recipe: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// URI indicating what type of recipe was performed. It determines the meaning
  /// of recipe.entryPoint, recipe.arguments, recipe.environment, and materials.
  public var type: Swift.String = Swift.String()

  /// Index in materials containing the recipe steps that are not implied by
  /// recipe.type. For example, if the recipe type were "make", then this would
  /// point to the source containing the Makefile, not the make program itself.
  /// Set to -1 if the recipe doesn't come from a material, as zero is default
  /// unset value for int64.
  public var definedInMaterial: Swift.Int64 = Swift.Int64()

  /// String identifying the entry point into the build.
  /// This is often a path to a configuration file and/or a target label within
  /// that file. The syntax and meaning are defined by recipe.type. For example,
  /// if the recipe type were "make", then this would reference the directory in
  /// which to run make as well as which target to use.
  public var entryPoint: Swift.String = Swift.String()

  /// Collection of all external inputs that influenced the build on top of
  /// recipe.definedInMaterial and recipe.entryPoint. For example, if the recipe
  /// type were "make", then this might be the flags passed to make aside from
  /// the target, which is captured in recipe.entryPoint. Since the arguments
  /// field can greatly vary in structure, depending on the builder and recipe
  /// type, this is of form "Any".
  public var arguments: [GoogleWKT.WKTAny] = []

  /// Any other builder-controlled inputs necessary for correctly evaluating the
  /// recipe. Usually only needed for reproducing the build but not evaluated as
  /// part of policy. Since the environment field can greatly vary in structure,
  /// depending on the builder and recipe type, this is of form "Any".
  public var environment: [GoogleWKT.WKTAny] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Recipe`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Recipe().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let definedInMaterial = CodingKeys(stringValue: "definedInMaterial")
    static let entryPoint = CodingKeys(stringValue: "entryPoint")
    static let arguments = CodingKeys(stringValue: "arguments")
    static let environment = CodingKeys(stringValue: "environment")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "definedInMaterial",
      "entryPoint",
      "arguments",
      "environment",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .definedInMaterial) {
      self.definedInMaterial = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entryPoint) {
      self.entryPoint = value
    }
    if let value = try container.decodeIfPresent([GoogleWKT.WKTAny].self, forKey: .arguments) {
      self.arguments = value
    }
    if let value = try container.decodeIfPresent([GoogleWKT.WKTAny].self, forKey: .environment) {
      self.environment = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.definedInMaterial, forKey: .definedInMaterial)
    try container.encode(self.entryPoint, forKey: .entryPoint)
    try container.encode(self.arguments, forKey: .arguments)
    try container.encode(self.environment, forKey: .environment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Recipe"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
