// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A unique identifier for a Cloud Repo.
public struct RepoId: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A cloud repo can be identified by either its project ID and repository name
  /// combination, or its globally unique identifier.
  public var id: IdOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RepoId`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepoId().with { $0.projectRepoId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectRepoId = CodingKeys(stringValue: "projectRepoId")
    static let uid = CodingKeys(stringValue: "uid")

    static let _knownKeys: Set<Swift.String> = [
      "projectRepoId",
      "uid",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var id: IdOneOf? = nil
    let idCheckAndSet = {
      if id != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'id'"))
      }
      id = $0
    }
    if let projectRepoId = try container.decodeIfPresent(
      ProjectRepoId?.self, forKey: .projectRepoId)
    {
      try idCheckAndSet(.projectRepoId(projectRepoId))
    }
    if let uid = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      try idCheckAndSet(.uid(uid))
    }
    self.id = id
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.id {
      switch choice {
      case .projectRepoId(let value):
        try container.encode(value, forKey: .projectRepoId)
      case .uid(let value):
        try container.encode(value, forKey: .uid)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A cloud repo can be identified by either its project ID and repository name
  /// combination, or its globally unique identifier.
  public enum IdOneOf: Codable, Equatable, Sendable {
    /// A combination of a project ID and a repo name.
    indirect case projectRepoId(ProjectRepoId?)
    /// A server-assigned, globally unique identifier.
    case uid(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.RepoId"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
