// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A predicate which describes the SBOM being referenced.
public struct SbomReferenceIntotoPredicate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The person or system referring this predicate to the consumer.
  public var referrerId: Swift.String = Swift.String()

  /// The location of the SBOM.
  public var location: Swift.String = Swift.String()

  /// The mime type of the SBOM.
  public var mimeType: Swift.String = Swift.String()

  /// A map of algorithm to digest of the contents of the SBOM.
  public var digest: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SbomReferenceIntotoPredicate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SbomReferenceIntotoPredicate().with { $0.referrerId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let referrerId = CodingKeys(stringValue: "referrerId")
    static let location = CodingKeys(stringValue: "location")
    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let digest = CodingKeys(stringValue: "digest")

    static let _knownKeys: Set<Swift.String> = [
      "referrerId",
      "location",
      "mimeType",
      "digest",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .referrerId) {
      self.referrerId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .digest)
    {
      self.digest = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.referrerId, forKey: .referrerId)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.mimeType, forKey: .mimeType)
    try container.encode(self.digest, forKey: .digest)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SbomReferenceIntotoPredicate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
