// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct SlsaProvenanceZeroTwo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var builder: SlsaProvenanceZeroTwo.SlsaBuilder? = nil

  public var buildType: Swift.String = Swift.String()

  public var invocation: SlsaProvenanceZeroTwo.SlsaInvocation? = nil

  public var buildConfig: GoogleWKT.WKTStruct? = nil

  public var metadata: SlsaProvenanceZeroTwo.SlsaMetadata? = nil

  public var materials: [SlsaProvenanceZeroTwo.SlsaMaterial] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SlsaProvenanceZeroTwo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlsaProvenanceZeroTwo().with { $0.builder = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let builder = CodingKeys(stringValue: "builder")
    static let buildType = CodingKeys(stringValue: "buildType")
    static let invocation = CodingKeys(stringValue: "invocation")
    static let buildConfig = CodingKeys(stringValue: "buildConfig")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let materials = CodingKeys(stringValue: "materials")

    static let _knownKeys: Set<Swift.String> = [
      "builder",
      "buildType",
      "invocation",
      "buildConfig",
      "metadata",
      "materials",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.builder = try container.decodeIfPresent(
      SlsaProvenanceZeroTwo.SlsaBuilder.self, forKey: .builder)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .buildType) {
      self.buildType = value
    }
    self.invocation = try container.decodeIfPresent(
      SlsaProvenanceZeroTwo.SlsaInvocation.self, forKey: .invocation)
    self.buildConfig = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .buildConfig)
    self.metadata = try container.decodeIfPresent(
      SlsaProvenanceZeroTwo.SlsaMetadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(
      [SlsaProvenanceZeroTwo.SlsaMaterial].self, forKey: .materials)
    {
      self.materials = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.builder, forKey: .builder)
    try container.encode(self.buildType, forKey: .buildType)
    try container.encodeIfPresent(self.invocation, forKey: .invocation)
    try container.encodeIfPresent(self.buildConfig, forKey: .buildConfig)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.materials, forKey: .materials)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Identifies the entity that executed the recipe, which is trusted to have
  /// correctly performed the operation and populated this provenance.
  public struct SlsaBuilder: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var id: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaBuilder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaBuilder().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")

      static let _knownKeys: Set<Swift.String> = [
        "id"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaBuilder"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The collection of artifacts that influenced the build including sources,
  /// dependencies, build tools, base images, and so on.
  public struct SlsaMaterial: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaMaterial`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaMaterial().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uri = CodingKeys(stringValue: "uri")
      static let digest = CodingKeys(stringValue: "digest")

      static let _knownKeys: Set<Swift.String> = [
        "uri",
        "digest",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .digest)
      {
        self.digest = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uri, forKey: .uri)
      try container.encode(self.digest, forKey: .digest)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaMaterial"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Identifies the event that kicked off the build.
  public struct SlsaInvocation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var configSource: SlsaProvenanceZeroTwo.SlsaConfigSource? = nil

    public var parameters: GoogleWKT.WKTStruct? = nil

    public var environment: GoogleWKT.WKTStruct? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaInvocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaInvocation().with { $0.configSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let configSource = CodingKeys(stringValue: "configSource")
      static let parameters = CodingKeys(stringValue: "parameters")
      static let environment = CodingKeys(stringValue: "environment")

      static let _knownKeys: Set<Swift.String> = [
        "configSource",
        "parameters",
        "environment",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.configSource = try container.decodeIfPresent(
        SlsaProvenanceZeroTwo.SlsaConfigSource.self, forKey: .configSource)
      self.parameters = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .parameters)
      self.environment = try container.decodeIfPresent(
        GoogleWKT.WKTStruct.self, forKey: .environment)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.configSource, forKey: .configSource)
      try container.encodeIfPresent(self.parameters, forKey: .parameters)
      try container.encodeIfPresent(self.environment, forKey: .environment)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaInvocation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes where the config file that kicked off the build came from.
  /// This is effectively a pointer to the source where buildConfig came from.
  public struct SlsaConfigSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    public var entryPoint: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaConfigSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaConfigSource().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uri = CodingKeys(stringValue: "uri")
      static let digest = CodingKeys(stringValue: "digest")
      static let entryPoint = CodingKeys(stringValue: "entryPoint")

      static let _knownKeys: Set<Swift.String> = [
        "uri",
        "digest",
        "entryPoint",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .digest)
      {
        self.digest = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entryPoint) {
        self.entryPoint = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uri, forKey: .uri)
      try container.encode(self.digest, forKey: .digest)
      try container.encode(self.entryPoint, forKey: .entryPoint)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaConfigSource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Other properties of the build.
  public struct SlsaMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var buildInvocationId: Swift.String = Swift.String()

    public var buildStartedOn: GoogleWKT.WKTTimestamp? = nil

    public var buildFinishedOn: GoogleWKT.WKTTimestamp? = nil

    public var completeness: SlsaProvenanceZeroTwo.SlsaCompleteness? = nil

    public var reproducible: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaMetadata().with { $0.buildInvocationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let buildInvocationId = CodingKeys(stringValue: "buildInvocationId")
      static let buildStartedOn = CodingKeys(stringValue: "buildStartedOn")
      static let buildFinishedOn = CodingKeys(stringValue: "buildFinishedOn")
      static let completeness = CodingKeys(stringValue: "completeness")
      static let reproducible = CodingKeys(stringValue: "reproducible")

      static let _knownKeys: Set<Swift.String> = [
        "buildInvocationId",
        "buildStartedOn",
        "buildFinishedOn",
        "completeness",
        "reproducible",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .buildInvocationId) {
        self.buildInvocationId = value
      }
      self.buildStartedOn = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .buildStartedOn)
      self.buildFinishedOn = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .buildFinishedOn)
      self.completeness = try container.decodeIfPresent(
        SlsaProvenanceZeroTwo.SlsaCompleteness.self, forKey: .completeness)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reproducible) {
        self.reproducible = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.buildInvocationId, forKey: .buildInvocationId)
      try container.encodeIfPresent(self.buildStartedOn, forKey: .buildStartedOn)
      try container.encodeIfPresent(self.buildFinishedOn, forKey: .buildFinishedOn)
      try container.encodeIfPresent(self.completeness, forKey: .completeness)
      try container.encode(self.reproducible, forKey: .reproducible)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Indicates that the builder claims certain fields in this message to be
  /// complete.
  public struct SlsaCompleteness: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var parameters: Swift.Bool = Swift.Bool()

    public var environment: Swift.Bool = Swift.Bool()

    public var materials: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SlsaCompleteness`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaCompleteness().with { $0.parameters = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parameters = CodingKeys(stringValue: "parameters")
      static let environment = CodingKeys(stringValue: "environment")
      static let materials = CodingKeys(stringValue: "materials")

      static let _knownKeys: Set<Swift.String> = [
        "parameters",
        "environment",
        "materials",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .parameters) {
        self.parameters = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .environment) {
        self.environment = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .materials) {
        self.materials = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parameters, forKey: .parameters)
      try container.encode(self.environment, forKey: .environment)
      try container.encode(self.materials, forKey: .materials)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaCompleteness"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
