// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A SourceContext is a reference to a tree of files. A SourceContext together
/// with a path point to a unique revision of a single file or directory.
public struct SourceContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Labels with user defined metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A SourceContext can refer any one of the following types of repositories.
  public var context: OneOf_Context? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SourceContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceContext().with { $0.cloudRepo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudRepo = CodingKeys(stringValue: "cloudRepo")
    static let gerrit = CodingKeys(stringValue: "gerrit")
    static let git = CodingKeys(stringValue: "git")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "cloudRepo",
      "gerrit",
      "git",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }

    var context: OneOf_Context? = nil
    let contextCheckAndSet = {
      if context != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'context'"))
      }
      context = $0
    }
    if let cloudRepo = try container.decodeIfPresent(
      CloudRepoSourceContext?.self, forKey: .cloudRepo)
    {
      try contextCheckAndSet(.cloudRepo(cloudRepo))
    }
    if let gerrit = try container.decodeIfPresent(GerritSourceContext?.self, forKey: .gerrit) {
      try contextCheckAndSet(.gerrit(gerrit))
    }
    if let git = try container.decodeIfPresent(GitSourceContext?.self, forKey: .git) {
      try contextCheckAndSet(.git(git))
    }
    self.context = context
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.context {
      switch choice {
      case .cloudRepo(let value):
        try container.encode(value, forKey: .cloudRepo)
      case .gerrit(let value):
        try container.encode(value, forKey: .gerrit)
      case .git(let value):
        try container.encode(value, forKey: .git)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A SourceContext can refer any one of the following types of repositories.
  public enum OneOf_Context: Codable, Equatable, Sendable {
    /// A SourceContext referring to a revision in a Google Cloud Source Repo.
    indirect case cloudRepo(CloudRepoSourceContext?)
    /// A SourceContext referring to a Gerrit project.
    indirect case gerrit(GerritSourceContext?)
    /// A SourceContext referring to any third party Git repo (e.g., GitHub).
    indirect case git(GitSourceContext?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SourceContext"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
