// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An Upgrade Note represents a potential upgrade of a package to a given
/// version. For each package version combination (i.e. bash 4.0, bash 4.1,
/// bash 4.1.2), there will be an Upgrade Note. For Windows, windows_update field
/// represents the information related to the update.
public struct UpgradeNote: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required for non-Windows OS. The package this Upgrade is for.
  public var `package`: Swift.String = Swift.String()

  /// Required for non-Windows OS. The version of the package in machine + human
  /// readable form.
  public var version: Version? = nil

  /// Metadata about the upgrade for each specific operating system.
  public var distributions: [UpgradeDistribution] = []

  /// Required for Windows OS. Represents the metadata about the Windows update.
  public var windowsUpdate: WindowsUpdate? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpgradeNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeNote().with { $0.`package` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let `package` = CodingKeys(stringValue: "package")
    static let version = CodingKeys(stringValue: "version")
    static let distributions = CodingKeys(stringValue: "distributions")
    static let windowsUpdate = CodingKeys(stringValue: "windowsUpdate")

    static let _knownKeys: Set<Swift.String> = [
      "package",
      "version",
      "distributions",
      "windowsUpdate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`package`) {
      self.`package` = value
    }
    self.version = try container.decodeIfPresent(Version.self, forKey: .version)
    if let value = try container.decodeIfPresent([UpgradeDistribution].self, forKey: .distributions)
    {
      self.distributions = value
    }
    self.windowsUpdate = try container.decodeIfPresent(WindowsUpdate.self, forKey: .windowsUpdate)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`package`, forKey: .`package`)
    try container.encodeIfPresent(self.version, forKey: .version)
    try container.encode(self.distributions, forKey: .distributions)
    try container.encodeIfPresent(self.windowsUpdate, forKey: .windowsUpdate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.UpgradeNote"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
