// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Version contains structured information about the version of a package.
public struct Version: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Used to correct mistakes in the version numbering scheme.
  public var epoch: Swift.Int32 = Swift.Int32()

  /// Required only when version kind is NORMAL. The main part of the version
  /// name.
  public var name: Swift.String = Swift.String()

  /// The iteration of the package build from the above version.
  public var revision: Swift.String = Swift.String()

  /// Whether this version is specifying part of an inclusive range. Grafeas
  /// does not have the capability to specify version ranges; instead we have
  /// fields that specify start version and end versions. At times this is
  /// insufficient - we also need to specify whether the version is included in
  /// the range or is excluded from the range. This boolean is expected to be set
  /// to true when the version is included in a range.
  public var inclusive: Swift.Bool = Swift.Bool()

  /// Required. Distinguishes between sentinel MIN/MAX versions and normal
  /// versions.
  public var kind: Version.VersionKind = Version.VersionKind()

  /// Human readable version string. This string is of the form
  /// <epoch>:<name>-<revision> and is only set when kind is NORMAL.
  public var fullName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Version`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Version().with { $0.epoch = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let epoch = CodingKeys(stringValue: "epoch")
    static let name = CodingKeys(stringValue: "name")
    static let revision = CodingKeys(stringValue: "revision")
    static let inclusive = CodingKeys(stringValue: "inclusive")
    static let kind = CodingKeys(stringValue: "kind")
    static let fullName = CodingKeys(stringValue: "fullName")

    static let _knownKeys: Set<Swift.String> = [
      "epoch",
      "name",
      "revision",
      "inclusive",
      "kind",
      "fullName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .epoch) {
      self.epoch = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revision) {
      self.revision = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .inclusive) {
      self.inclusive = value
    }
    if let value = try container.decodeIfPresent(Version.VersionKind.self, forKey: .kind) {
      self.kind = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullName) {
      self.fullName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.epoch, forKey: .epoch)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.revision, forKey: .revision)
    try container.encode(self.inclusive, forKey: .inclusive)
    try container.encode(self.kind, forKey: .kind)
    try container.encode(self.fullName, forKey: .fullName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Whether this is an ordinary package version or a sentinel MIN/MAX version.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum VersionKind: Codable, Equatable, Hashable, Sendable {
    /// Unknown.
    case unspecified
    /// A standard package version.
    case normal
    /// A special version representing negative infinity.
    case minimum
    /// A special version representing positive infinity.
    case maximum
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .normal: return 1
      case .minimum: return 2
      case .maximum: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VERSION_KIND_UNSPECIFIED"
      case .normal: return "NORMAL"
      case .minimum: return "MINIMUM"
      case .maximum: return "MAXIMUM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VersionKind/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VERSION_KIND_UNSPECIFIED": self = .unspecified
      case "NORMAL": self = .normal
      case "MINIMUM": self = .minimum
      case "MAXIMUM": self = .maximum
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VersionKind/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .normal
      case 2: self = .minimum
      case 3: self = .maximum
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VERSION_KIND_UNSPECIFIED")
      case .normal: return try container.encode("NORMAL")
      case .minimum: return try container.encode("MINIMUM")
      case .maximum: return try container.encode("MAXIMUM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Version"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
