// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Windows Update represents the metadata about the update for the Windows
/// operating system. The fields in this message come from the Windows Update API
/// documented at
/// https://docs.microsoft.com/en-us/windows/win32/api/wuapi/nn-wuapi-iupdate.
public struct WindowsUpdate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required - The unique identifier for the update.
  public var identity: WindowsUpdate.Identity? = nil

  /// The localized title of the update.
  public var title: Swift.String = Swift.String()

  /// The localized description of the update.
  public var description: Swift.String = Swift.String()

  /// The list of categories to which the update belongs.
  public var categories: [WindowsUpdate.Category] = []

  /// The Microsoft Knowledge Base article IDs that are associated with the
  /// update.
  public var kbArticleIds: [Swift.String] = []

  /// The hyperlink to the support information for the update.
  public var supportUrl: Swift.String = Swift.String()

  /// The last published timestamp of the update.
  public var lastPublishedTimestamp: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WindowsUpdate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WindowsUpdate().with { $0.identity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let identity = CodingKeys(stringValue: "identity")
    static let title = CodingKeys(stringValue: "title")
    static let description = CodingKeys(stringValue: "description")
    static let categories = CodingKeys(stringValue: "categories")
    static let kbArticleIds = CodingKeys(stringValue: "kbArticleIds")
    static let supportUrl = CodingKeys(stringValue: "supportUrl")
    static let lastPublishedTimestamp = CodingKeys(stringValue: "lastPublishedTimestamp")

    static let _knownKeys: Set<Swift.String> = [
      "identity",
      "title",
      "description",
      "categories",
      "kbArticleIds",
      "supportUrl",
      "lastPublishedTimestamp",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.identity = try container.decodeIfPresent(WindowsUpdate.Identity.self, forKey: .identity)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([WindowsUpdate.Category].self, forKey: .categories)
    {
      self.categories = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .kbArticleIds) {
      self.kbArticleIds = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .supportUrl) {
      self.supportUrl = value
    }
    self.lastPublishedTimestamp = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastPublishedTimestamp)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.identity, forKey: .identity)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.categories, forKey: .categories)
    try container.encode(self.kbArticleIds, forKey: .kbArticleIds)
    try container.encode(self.supportUrl, forKey: .supportUrl)
    try container.encodeIfPresent(self.lastPublishedTimestamp, forKey: .lastPublishedTimestamp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The unique identifier of the update.
  public struct Identity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The revision independent identifier of the update.
    public var updateId: Swift.String = Swift.String()

    /// The revision number of the update.
    public var revision: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Identity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Identity().with { $0.updateId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let updateId = CodingKeys(stringValue: "updateId")
      static let revision = CodingKeys(stringValue: "revision")

      static let _knownKeys: Set<Swift.String> = [
        "updateId",
        "revision",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .updateId) {
        self.updateId = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .revision) {
        self.revision = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.updateId, forKey: .updateId)
      try container.encode(self.revision, forKey: .revision)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.WindowsUpdate.Identity"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The category to which the update belongs.
  public struct Category: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The identifier of the category.
    public var categoryId: Swift.String = Swift.String()

    /// The localized name of the category.
    public var name: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Category`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Category().with { $0.categoryId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let categoryId = CodingKeys(stringValue: "categoryId")
      static let name = CodingKeys(stringValue: "name")

      static let _knownKeys: Set<Swift.String> = [
        "categoryId",
        "name",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .categoryId) {
        self.categoryId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.categoryId, forKey: .categoryId)
      try container.encode(self.name, forKey: .name)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.WindowsUpdate.Category"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.WindowsUpdate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
